apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
  - maintenance-deployment.yml

configMapGenerator:
  - name: maintenance-page
    files:
      - index.html=maintenance-page.html

generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      - op: replace
        path: /spec/defaultBackend/service/name
        value: maintenance
    target:
      kind: Ingress
      name: web-funnel
