// AUTO-GENERATED from the BSB USX seed (scripts/gen-canon.mjs). The 66-book
// canon registry: USFM codes, url slugs, display names, chapter counts, and
// reference-lookup aliases. Used by the reference parser (client) and the reader
// navigation. Regenerate if the seed translation changes.

export type CanonBook = {
  code: string; // USFM code, e.g. "PHP"
  slug: string; // url slug, e.g. "philippians"
  name: string; // display name, e.g. "Philippians"
  longName: string;
  testament: 'OT' | 'NT';
  ordinal: number; // 1..66
  chapterCount: number;
  aliases: string[]; // lowercased, punctuation-stripped lookup keys
};

export const CANON: CanonBook[] = [
  {
    code: 'GEN',
    slug: 'genesis',
    name: 'Genesis',
    longName: 'Genesis',
    testament: 'OT',
    ordinal: 1,
    chapterCount: 50,
    aliases: ['gen', 'gn'],
  },
  {
    code: 'EXO',
    slug: 'exodus',
    name: 'Exodus',
    longName: 'Exodus',
    testament: 'OT',
    ordinal: 2,
    chapterCount: 40,
    aliases: ['exo', 'ex', 'exod'],
  },
  {
    code: 'LEV',
    slug: 'leviticus',
    name: 'Leviticus',
    longName: 'Leviticus',
    testament: 'OT',
    ordinal: 3,
    chapterCount: 27,
    aliases: ['lev', 'lv'],
  },
  {
    code: 'NUM',
    slug: 'numbers',
    name: 'Numbers',
    longName: 'Numbers',
    testament: 'OT',
    ordinal: 4,
    chapterCount: 36,
    aliases: ['num', 'nm', 'nb'],
  },
  {
    code: 'DEU',
    slug: 'deuteronomy',
    name: 'Deuteronomy',
    longName: 'Deuteronomy',
    testament: 'OT',
    ordinal: 5,
    chapterCount: 34,
    aliases: ['deu', 'dt', 'deut'],
  },
  {
    code: 'JOS',
    slug: 'joshua',
    name: 'Joshua',
    longName: 'Joshua',
    testament: 'OT',
    ordinal: 6,
    chapterCount: 24,
    aliases: ['jos', 'jsh', 'josh'],
  },
  {
    code: 'JDG',
    slug: 'judges',
    name: 'Judges',
    longName: 'Judges',
    testament: 'OT',
    ordinal: 7,
    chapterCount: 21,
    aliases: ['jdg', 'judg'],
  },
  {
    code: 'RUT',
    slug: 'ruth',
    name: 'Ruth',
    longName: 'Ruth',
    testament: 'OT',
    ordinal: 8,
    chapterCount: 4,
    aliases: ['rut', 'rth', 'ru'],
  },
  {
    code: '1SA',
    slug: '1-samuel',
    name: '1 Samuel',
    longName: '1 Samuel',
    testament: 'OT',
    ordinal: 9,
    chapterCount: 31,
    aliases: ['1sa', '1sam', '1sm'],
  },
  {
    code: '2SA',
    slug: '2-samuel',
    name: '2 Samuel',
    longName: '2 Samuel',
    testament: 'OT',
    ordinal: 10,
    chapterCount: 24,
    aliases: ['2sa', '2sam', '2sm'],
  },
  {
    code: '1KI',
    slug: '1-kings',
    name: '1 Kings',
    longName: '1 Kings',
    testament: 'OT',
    ordinal: 11,
    chapterCount: 22,
    aliases: ['1ki', '1kgs', '1kg'],
  },
  {
    code: '2KI',
    slug: '2-kings',
    name: '2 Kings',
    longName: '2 Kings',
    testament: 'OT',
    ordinal: 12,
    chapterCount: 25,
    aliases: ['2ki', '2kgs', '2kg'],
  },
  {
    code: '1CH',
    slug: '1-chronicles',
    name: '1 Chronicles',
    longName: '1 Chronicles',
    testament: 'OT',
    ordinal: 13,
    chapterCount: 29,
    aliases: ['1ch', '1chr', '1chron'],
  },
  {
    code: '2CH',
    slug: '2-chronicles',
    name: '2 Chronicles',
    longName: '2 Chronicles',
    testament: 'OT',
    ordinal: 14,
    chapterCount: 36,
    aliases: ['2ch', '2chr', '2chron'],
  },
  {
    code: 'EZR',
    slug: 'ezra',
    name: 'Ezra',
    longName: 'Ezra',
    testament: 'OT',
    ordinal: 15,
    chapterCount: 10,
    aliases: ['ezr'],
  },
  {
    code: 'NEH',
    slug: 'nehemiah',
    name: 'Nehemiah',
    longName: 'Nehemiah',
    testament: 'OT',
    ordinal: 16,
    chapterCount: 13,
    aliases: ['neh', 'ne'],
  },
  {
    code: 'EST',
    slug: 'esther',
    name: 'Esther',
    longName: 'Esther',
    testament: 'OT',
    ordinal: 17,
    chapterCount: 10,
    aliases: ['est', 'esth'],
  },
  {
    code: 'JOB',
    slug: 'job',
    name: 'Job',
    longName: 'Job',
    testament: 'OT',
    ordinal: 18,
    chapterCount: 42,
    aliases: ['job', 'jb'],
  },
  {
    code: 'PSA',
    slug: 'psalm',
    name: 'Psalm',
    longName: 'Psalm',
    testament: 'OT',
    ordinal: 19,
    chapterCount: 150,
    aliases: ['psa', 'ps', 'psalm', 'psalms', 'pss'],
  },
  {
    code: 'PRO',
    slug: 'proverbs',
    name: 'Proverbs',
    longName: 'Proverbs',
    testament: 'OT',
    ordinal: 20,
    chapterCount: 31,
    aliases: ['pro', 'pr', 'prov', 'prv'],
  },
  {
    code: 'ECC',
    slug: 'ecclesiastes',
    name: 'Ecclesiastes',
    longName: 'Ecclesiastes',
    testament: 'OT',
    ordinal: 21,
    chapterCount: 12,
    aliases: ['ecc', 'ec', 'eccl', 'qoh'],
  },
  {
    code: 'SNG',
    slug: 'song-of-solomon',
    name: 'Song of Solomon',
    longName: 'Song of Solomon',
    testament: 'OT',
    ordinal: 22,
    chapterCount: 8,
    aliases: ['sng', 'song', 'songs', 'sos', 'canticles'],
  },
  {
    code: 'ISA',
    slug: 'isaiah',
    name: 'Isaiah',
    longName: 'Isaiah',
    testament: 'OT',
    ordinal: 23,
    chapterCount: 66,
    aliases: ['isa', 'is'],
  },
  {
    code: 'JER',
    slug: 'jeremiah',
    name: 'Jeremiah',
    longName: 'Jeremiah',
    testament: 'OT',
    ordinal: 24,
    chapterCount: 52,
    aliases: ['jer', 'je'],
  },
  {
    code: 'LAM',
    slug: 'lamentations',
    name: 'Lamentations',
    longName: 'Lamentations',
    testament: 'OT',
    ordinal: 25,
    chapterCount: 5,
    aliases: ['lam', 'la'],
  },
  {
    code: 'EZK',
    slug: 'ezekiel',
    name: 'Ezekiel',
    longName: 'Ezekiel',
    testament: 'OT',
    ordinal: 26,
    chapterCount: 48,
    aliases: ['ezk', 'ezek', 'eze'],
  },
  {
    code: 'DAN',
    slug: 'daniel',
    name: 'Daniel',
    longName: 'Daniel',
    testament: 'OT',
    ordinal: 27,
    chapterCount: 12,
    aliases: ['dan', 'da', 'dn'],
  },
  {
    code: 'HOS',
    slug: 'hosea',
    name: 'Hosea',
    longName: 'Hosea',
    testament: 'OT',
    ordinal: 28,
    chapterCount: 14,
    aliases: ['hos', 'ho'],
  },
  {
    code: 'JOL',
    slug: 'joel',
    name: 'Joel',
    longName: 'Joel',
    testament: 'OT',
    ordinal: 29,
    chapterCount: 3,
    aliases: ['jol', 'joel', 'jl'],
  },
  {
    code: 'AMO',
    slug: 'amos',
    name: 'Amos',
    longName: 'Amos',
    testament: 'OT',
    ordinal: 30,
    chapterCount: 9,
    aliases: ['amo', 'am', 'amos'],
  },
  {
    code: 'OBA',
    slug: 'obadiah',
    name: 'Obadiah',
    longName: 'Obadiah',
    testament: 'OT',
    ordinal: 31,
    chapterCount: 1,
    aliases: ['oba', 'ob', 'obad'],
  },
  {
    code: 'JON',
    slug: 'jonah',
    name: 'Jonah',
    longName: 'Jonah',
    testament: 'OT',
    ordinal: 32,
    chapterCount: 4,
    aliases: ['jon', 'jnh'],
  },
  {
    code: 'MIC',
    slug: 'micah',
    name: 'Micah',
    longName: 'Micah',
    testament: 'OT',
    ordinal: 33,
    chapterCount: 7,
    aliases: ['mic', 'mc'],
  },
  {
    code: 'NAM',
    slug: 'nahum',
    name: 'Nahum',
    longName: 'Nahum',
    testament: 'OT',
    ordinal: 34,
    chapterCount: 3,
    aliases: ['nam', 'na', 'nah'],
  },
  {
    code: 'HAB',
    slug: 'habakkuk',
    name: 'Habakkuk',
    longName: 'Habakkuk',
    testament: 'OT',
    ordinal: 35,
    chapterCount: 3,
    aliases: ['hab', 'hb'],
  },
  {
    code: 'ZEP',
    slug: 'zephaniah',
    name: 'Zephaniah',
    longName: 'Zephaniah',
    testament: 'OT',
    ordinal: 36,
    chapterCount: 3,
    aliases: ['zep', 'zeph'],
  },
  {
    code: 'HAG',
    slug: 'haggai',
    name: 'Haggai',
    longName: 'Haggai',
    testament: 'OT',
    ordinal: 37,
    chapterCount: 2,
    aliases: ['hag', 'hg'],
  },
  {
    code: 'ZEC',
    slug: 'zechariah',
    name: 'Zechariah',
    longName: 'Zechariah',
    testament: 'OT',
    ordinal: 38,
    chapterCount: 14,
    aliases: ['zec', 'zech'],
  },
  {
    code: 'MAL',
    slug: 'malachi',
    name: 'Malachi',
    longName: 'Malachi',
    testament: 'OT',
    ordinal: 39,
    chapterCount: 4,
    aliases: ['mal', 'ml'],
  },
  {
    code: 'MAT',
    slug: 'matthew',
    name: 'Matthew',
    longName: 'The Gospel According to Matthew',
    testament: 'NT',
    ordinal: 40,
    chapterCount: 28,
    aliases: ['mat', 'mt', 'matt'],
  },
  {
    code: 'MRK',
    slug: 'mark',
    name: 'Mark',
    longName: 'The Gospel According to Mark',
    testament: 'NT',
    ordinal: 41,
    chapterCount: 16,
    aliases: ['mrk', 'mk', 'mark', 'mar'],
  },
  {
    code: 'LUK',
    slug: 'luke',
    name: 'Luke',
    longName: 'The Gospel According to Luke',
    testament: 'NT',
    ordinal: 42,
    chapterCount: 24,
    aliases: ['luk', 'lk', 'luke'],
  },
  {
    code: 'JHN',
    slug: 'john',
    name: 'John',
    longName: 'The Gospel According to John',
    testament: 'NT',
    ordinal: 43,
    chapterCount: 21,
    aliases: ['jhn', 'jn', 'john'],
  },
  {
    code: 'ACT',
    slug: 'acts',
    name: 'Acts',
    longName: 'The Acts of the Apostles',
    testament: 'NT',
    ordinal: 44,
    chapterCount: 28,
    aliases: ['act', 'ac', 'acts'],
  },
  {
    code: 'ROM',
    slug: 'romans',
    name: 'Romans',
    longName: 'The Letter to the Romans',
    testament: 'NT',
    ordinal: 45,
    chapterCount: 16,
    aliases: ['rom', 'ro', 'rm'],
  },
  {
    code: '1CO',
    slug: '1-corinthians',
    name: '1 Corinthians',
    longName: 'The First Letter to the Corinthians',
    testament: 'NT',
    ordinal: 46,
    chapterCount: 16,
    aliases: ['1co', '1cor'],
  },
  {
    code: '2CO',
    slug: '2-corinthians',
    name: '2 Corinthians',
    longName: 'The Second Letter to the Corinthians',
    testament: 'NT',
    ordinal: 47,
    chapterCount: 13,
    aliases: ['2co', '2cor'],
  },
  {
    code: 'GAL',
    slug: 'galatians',
    name: 'Galatians',
    longName: 'The Letter to the Galatians',
    testament: 'NT',
    ordinal: 48,
    chapterCount: 6,
    aliases: ['gal', 'ga'],
  },
  {
    code: 'EPH',
    slug: 'ephesians',
    name: 'Ephesians',
    longName: 'The Letter to the Ephesians',
    testament: 'NT',
    ordinal: 49,
    chapterCount: 6,
    aliases: ['eph', 'ephes'],
  },
  {
    code: 'PHP',
    slug: 'philippians',
    name: 'Philippians',
    longName: 'The Letter to the Philippians',
    testament: 'NT',
    ordinal: 50,
    chapterCount: 4,
    aliases: ['php', 'phil', 'pp'],
  },
  {
    code: 'COL',
    slug: 'colossians',
    name: 'Colossians',
    longName: 'The Letter to the Colossians',
    testament: 'NT',
    ordinal: 51,
    chapterCount: 4,
    aliases: ['col'],
  },
  {
    code: '1TH',
    slug: '1-thessalonians',
    name: '1 Thessalonians',
    longName: 'The First Letter to the Thessalonians',
    testament: 'NT',
    ordinal: 52,
    chapterCount: 5,
    aliases: ['1th', '1thess', '1thes'],
  },
  {
    code: '2TH',
    slug: '2-thessalonians',
    name: '2 Thessalonians',
    longName: 'The Second Letter to the Thessalonians',
    testament: 'NT',
    ordinal: 53,
    chapterCount: 3,
    aliases: ['2th', '2thess', '2thes'],
  },
  {
    code: '1TI',
    slug: '1-timothy',
    name: '1 Timothy',
    longName: 'The First Letter to Timothy',
    testament: 'NT',
    ordinal: 54,
    chapterCount: 6,
    aliases: ['1ti', '1tim'],
  },
  {
    code: '2TI',
    slug: '2-timothy',
    name: '2 Timothy',
    longName: 'The Second Letter to Timothy',
    testament: 'NT',
    ordinal: 55,
    chapterCount: 4,
    aliases: ['2ti', '2tim'],
  },
  {
    code: 'TIT',
    slug: 'titus',
    name: 'Titus',
    longName: 'The Letter to Titus',
    testament: 'NT',
    ordinal: 56,
    chapterCount: 3,
    aliases: ['tit', 'ti'],
  },
  {
    code: 'PHM',
    slug: 'philemon',
    name: 'Philemon',
    longName: 'The Letter to Philemon',
    testament: 'NT',
    ordinal: 57,
    chapterCount: 1,
    aliases: ['phm', 'philem', 'phlm'],
  },
  {
    code: 'HEB',
    slug: 'hebrews',
    name: 'Hebrews',
    longName: 'The Letter to the Hebrews',
    testament: 'NT',
    ordinal: 58,
    chapterCount: 13,
    aliases: ['heb'],
  },
  {
    code: 'JAS',
    slug: 'james',
    name: 'James',
    longName: 'The Letter of James',
    testament: 'NT',
    ordinal: 59,
    chapterCount: 5,
    aliases: ['jas', 'jms', 'james'],
  },
  {
    code: '1PE',
    slug: '1-peter',
    name: '1 Peter',
    longName: 'The First Letter of Peter',
    testament: 'NT',
    ordinal: 60,
    chapterCount: 5,
    aliases: ['1pe', '1pet', '1pt'],
  },
  {
    code: '2PE',
    slug: '2-peter',
    name: '2 Peter',
    longName: 'The Second Letter of Peter',
    testament: 'NT',
    ordinal: 61,
    chapterCount: 3,
    aliases: ['2pe', '2pet', '2pt'],
  },
  {
    code: '1JN',
    slug: '1-john',
    name: '1 John',
    longName: 'The First Letter of John',
    testament: 'NT',
    ordinal: 62,
    chapterCount: 5,
    aliases: ['1jn', '1john', '1jhn'],
  },
  {
    code: '2JN',
    slug: '2-john',
    name: '2 John',
    longName: 'The Second Letter of John',
    testament: 'NT',
    ordinal: 63,
    chapterCount: 1,
    aliases: ['2jn', '2john'],
  },
  {
    code: '3JN',
    slug: '3-john',
    name: '3 John',
    longName: 'The Third Letter of John',
    testament: 'NT',
    ordinal: 64,
    chapterCount: 1,
    aliases: ['3jn', '3john'],
  },
  {
    code: 'JUD',
    slug: 'jude',
    name: 'Jude',
    longName: 'The Letter of Jude',
    testament: 'NT',
    ordinal: 65,
    chapterCount: 1,
    aliases: ['jud', 'jude'],
  },
  {
    code: 'REV',
    slug: 'revelation',
    name: 'Revelation',
    longName: 'The Revelation to John',
    testament: 'NT',
    ordinal: 66,
    chapterCount: 22,
    aliases: ['rev', 'rv', 'apoc', 'apocalypse'],
  },
];

const norm = (s: string) =>
  s
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');

const BY_SLUG = new Map(CANON.map((b) => [b.slug, b]));
const BY_KEY = new Map<string, CanonBook>();
for (const b of CANON) {
  BY_KEY.set(norm(b.slug), b);
  BY_KEY.set(norm(b.name), b);
  for (const a of b.aliases) {
    BY_KEY.set(norm(a), b);
  }
}

export function bookBySlug(slug: string): CanonBook | undefined {
  return BY_SLUG.get(slug);
}

// Resolve a book by slug, name, abbreviation, or USFM code (case/space/punct
// insensitive). Returns undefined when nothing matches.
export function findBook(query: string): CanonBook | undefined {
  return BY_KEY.get(norm(query));
}

export const OLD_TESTAMENT = CANON.filter((b) => b.testament === 'OT');
export const NEW_TESTAMENT = CANON.filter((b) => b.testament === 'NT');

// The reader's default landing passage.
export const DEFAULT_BOOK = 'john';
export const DEFAULT_CHAPTER = 1;
