#!/usr/bin/env bash

if echo $GIT_AUTHOR_EMAIL | grep 'lets.church$'; then
  if ! git config --get user.signingKey; then
    echo "Attempting to commit with @lets.church email with no signingKey configured!"
    exit 1
  fi
fi
