// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: misc.sql

package data

import (
	"context"
)

const getTrackingSalt = `-- name: GetTrackingSalt :one
SELECT salt FROM tracking_salt ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetTrackingSalt(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTrackingSalt)
	var salt int32
	err := row.Scan(&salt)
	return salt, err
}
