name = "web"
compatibility_date = "2023-02-12"

main = "./dist/server.js"

[site]
bucket = "./dist/public"

[env.preview]
route = "preview.lets.church"

[env.preview.vars]
GRAPHQL_URL = "https://gateway-preview.letschurch.cloud/graphql"
