variables:
  GIT_LFS_SKIP_SMUDGE: "1"

stages:
  - setup
  - check
  - test
  - build
  - deploy

.setup:
  activate_hermit: source ./bin/activate-hermit
  npmci: npm ci --cache $CI_PROJECT_DIR/.npm --prefer-offline

default:
  before_script:
    - !reference [.setup, activate_hermit]

#   ____ _   _ _____ ____ _  __
#  / ___| | | | ____/ ___| |/ /
# | |   | |_| |  _|| |   | ' /
# | |___|  _  | |__| |___| . \
#  \____|_| |_|_____\____|_|\_\

check-gateway:
  stage: check
  script:
    - cd $CI_PROJECT_DIR/services/gateway
    - !reference [.setup, npmci]
    - npm run check
  cache:
    key:
      files:
        - $CI_PROJECT_DIR/services/gateway/package-lock.json
    paths:
      - $CI_PROJECT_DIR/.npm

check-web:
  stage: check
  script:
    - cd $CI_PROJECT_DIR/apps/web
    - !reference [.setup, npmci]
    - npm run check
  cache:
    key:
      files:
        - $CI_PROJECT_DIR/apps/web/package-lock.json
    paths:
      - $CI_PROJECT_DIR/.npm

check-scripts:
  stage: check
  script:
    - cd $CI_PROJECT_DIR/scripts
    - !reference [.setup, npmci]
    - npm run check
  cache:
    key:
      files:
        - $CI_PROJECT_DIR/scripts/package-lock.json
    paths:
      - $CI_PROJECT_DIR/.npm

#  _____ _____ ____ _____
# |_   _| ____/ ___|_   _|
#   | | |  _| \___ \ | |
#   | | | |___ ___) || |
#   |_| |_____|____/ |_|

test-gateway:
  stage: test
  script:
    - cd services/gateway
    - !reference [.setup, npmci]
    - npm run test
  cache: !reference [check-gateway, cache]

#  ____  _   _ ___ _     ____
# | __ )| | | |_ _| |   |  _ \
# |  _ \| | | || || |   | | | |
# | |_) | |_| || || |___| |_| |
# |____/ \___/|___|_____|____/

.build-common: &build-common
  image: docker:24.0.1
  services:
    - docker:24.0.1-dind
  stage: build
  only:
    - kyrios
  before_script:
    - apk add --no-cache curl
    - curl https://depot.dev/install-cli.sh | DEPOT_INSTALL_DIR=/usr/local/bin sh
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-gateway:
  <<: *build-common
  script:
    - cd services/gateway
    - depot build --target server -t registry.gitlab.com/letschurch/lets.church/gateway:${CI_COMMIT_SHORT_SHA} . --push

build-background-worker:
  <<: *build-common
  script:
    - cd services/gateway
    - depot build --target background-worker -t registry.gitlab.com/letschurch/lets.church/background-worker:${CI_COMMIT_SHORT_SHA} . --push

build-import-worker:
  <<: *build-common
  script:
    - cd services/gateway
    - depot build --target import-worker -t registry.gitlab.com/letschurch/lets.church/import-worker:${CI_COMMIT_SHORT_SHA} . --push

build-transcode-worker:
  <<: *build-common
  script:
    - cd services/gateway
    - depot build --target transcode-worker -t registry.gitlab.com/letschurch/lets.church/transcode-worker:${CI_COMMIT_SHORT_SHA} . --push

# build-transcribe-worker:
#   <<: *build-common
#   script:
#     - cd services/gateway
#     - depot build --target transcribe-worker -t registry.gitlab.com/letschurch/lets.church/transcribe-worker:${CI_COMMIT_SHORT_SHA} . --push

build-web:
  <<: *build-common
  script:
    - cd apps/web
    - depot build -t registry.gitlab.com/letschurch/lets.church/web:${CI_COMMIT_SHORT_SHA} . --push

#  ____             _
# |  _ \  ___ _ __ | | ___  _   _
# | | | |/ _ \ '_ \| |/ _ \| | | |
# | |_| |  __/ |_) | | (_) | |_| |
# |____/ \___| .__/|_|\___/ \__, |
#            |_|            |___/

deploy-k8s:
  stage: deploy
  only:
    - kyrios
  image: debian:12.1
  before_script:
    - apt update
    - apt install -y bsdmainutils vim git git-lfs curl
    - source ./bin/activate-hermit
  script:
    - transcrypt -F -y -c $TRANSCRYPT_CIPHER -p $TRANSCRYPT_PASSWORD
    - cd infra/k8s/prod
    - just deploy-set-images prod $CI_COMMIT_SHORT_SHA
    - kubectl apply -k .
