packages:
  - "./packages/*"

catalog:
  "@biomejs/biome": "2.3.4"
  "@sentry/node": "^10.25.0"
  "@temporalio/activity": "^1.13.2"
  "@temporalio/client": "^1.13.2"
  "@temporalio/worker": "^1.13.2"
  "@temporalio/workflow": "^1.13.2"
  "@types/node": "^24.10.0"
  "@types/wait-on": "^5.3.4"
  "es-toolkit": "^1.41.0"
  "p-map": "^7.0.3"
  "p-retry": "^7.1.0"
  "pino": "^10.1.0"
  "tsx": "^4.20.6"
  "type-fest": "^5.2.0"
  "typescript": "^5.9.3"
  "uuid": "^13.0.0"
  "vitest": "^3.2.4"
  "wait-on": "^9.0.1"
  "xss": "^1.0.15"
  "zod": "^4.1.12"
