// Type-only exports from Prisma client for use in client-side code
// These exports don't include the PrismaClient itself, so they're safe for browser bundles
// We import from browser.ts and enums.ts which are generated by Prisma for browser use

export type {
  AppUser,
  Channel,
  ChannelMembership,
  Organization,
  OrganizationMembership,
  Prisma,
  UploadList,
  UploadListEntry,
  UploadRecord as Upload,
  UploadUserComment as Comment,
  UploadUserCommentRating as CommentVote,
  UploadView,
} from './generated/prisma/browser';

export type { AppUserRole as UserRole } from './generated/prisma/enums';

export {
  ChannelVisibility,
  UploadLicense,
  UploadListType,
  UploadViewSource,
  UploadVisibility,
} from './generated/prisma/enums';
