/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibleIndexRouteImport } from './routes/bible.index'
import { Route as TrpcSplatRouteImport } from './routes/trpc.$'
import { Route as ApiAnswerRouteImport } from './routes/api/answer'
import { Route as CompareBookChapterRouteImport } from './routes/compare.$book.$chapter'
import { Route as BibleBookChapterRouteImport } from './routes/bible.$book.$chapter'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrpcSplatRoute = TrpcSplatRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnswerRoute = ApiAnswerRouteImport.update({
  id: '/api/answer',
  path: '/api/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBookChapterRoute = CompareBookChapterRouteImport.update({
  id: '/compare/$book/$chapter',
  path: '/compare/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookChapterRoute = BibleBookChapterRouteImport.update({
  id: '/bible/$book/$chapter',
  path: '/bible/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/library': typeof LibraryRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/answer': typeof ApiAnswerRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/bible/': typeof BibleIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/compare/$book/$chapter': typeof CompareBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/library': typeof LibraryRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/answer': typeof ApiAnswerRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/bible': typeof BibleIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/compare/$book/$chapter': typeof CompareBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/library': typeof LibraryRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/answer': typeof ApiAnswerRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/bible/': typeof BibleIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/compare/$book/$chapter': typeof CompareBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/library'
    | '/listen'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/api/answer'
    | '/trpc/$'
    | '/bible/'
    | '/bible/$book/$chapter'
    | '/compare/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/library'
    | '/listen'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/api/answer'
    | '/trpc/$'
    | '/bible'
    | '/bible/$book/$chapter'
    | '/compare/$book/$chapter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/callback'
    | '/library'
    | '/listen'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/api/answer'
    | '/trpc/$'
    | '/bible/'
    | '/bible/$book/$chapter'
    | '/compare/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  LibraryRoute: typeof LibraryRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiAnswerRoute: typeof ApiAnswerRoute
  TrpcSplatRoute: typeof TrpcSplatRoute
  BibleIndexRoute: typeof BibleIndexRoute
  BibleBookChapterRoute: typeof BibleBookChapterRoute
  CompareBookChapterRoute: typeof CompareBookChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/answer': {
      id: '/api/answer'
      path: '/api/answer'
      fullPath: '/api/answer'
      preLoaderRoute: typeof ApiAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$book/$chapter': {
      id: '/compare/$book/$chapter'
      path: '/compare/$book/$chapter'
      fullPath: '/compare/$book/$chapter'
      preLoaderRoute: typeof CompareBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$book/$chapter': {
      id: '/bible/$book/$chapter'
      path: '/bible/$book/$chapter'
      fullPath: '/bible/$book/$chapter'
      preLoaderRoute: typeof BibleBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  LibraryRoute: LibraryRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiAnswerRoute: ApiAnswerRoute,
  TrpcSplatRoute: TrpcSplatRoute,
  BibleIndexRoute: BibleIndexRoute,
  BibleBookChapterRoute: BibleBookChapterRoute,
  CompareBookChapterRoute: CompareBookChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
