apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local
resources:
  - ../base
configMapGenerator:
  - name: gateway-config
    behavior: merge
    literals:
      - MEDIA_URL="https://media-preview.letschurch.cloud"
secretGenerator:
  - name: postgres-credentials
    literals:
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgres://letschurch:password@postgres:5432/letschurch
  - name: temporal-server-secrets
    literals:
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=password
  - name: jwt-secret
    literals:
      - JWT_SECRET=a5f09624d6106947a62e904ef1f31d880e3c4dde7ac74d67828c197a7f72ec973ca5ccae1210ddad78e590b3734511c0a943fe8ed366640ffb09d5edc9da097a
  - name: s3-secret
    envs:
      - s3.env
  - name: smtp-secret
    envs:
      - smtp.env
  - name: init-sql
    files:
      - init.sql
