version: v0.10.1

dsn: memory

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

serve:
  public:
    base_url: null # SERVE_PUBLIC_BASE_URL
    port: null # SERVE_PUBLIC_PORT
    cors:
      enabled: true
  admin:
    base_url: null # SERVE_ADMIN_BASE_URL
    port: null # SERVE_ADMIN_PORT

selfservice:
  default_browser_return_url: null # SELFSERVICE_DEFAULT_BROWSER_RETURN_URL

  allowed_return_urls:
    - null # SELFSERVICE_ALLOWED_RETURN_URLS_0

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: true
        min_password_length: 8
        identifier_similarity_check_enabled: true

  flows:
    error:
      ui_url: null # SELFSERVICE_FLOWS_ERROR_UI_URL

    settings:
      ui_url: null # SELFSERVICE_FLOWS_SETTINGS_UI_URL
      privileged_session_max_age: 15m

    recovery:
      ui_url: null # SELFSERVICE_FLOWS_RECOVERY_UI_URL
      enabled: true

    verification:
      ui_url: null # SELFSERVICE_FLOWS_VERIFICATION_UI_URL
      enabled: true

    login:
      ui_url: null # SELFSERVICE_FLOWS_LOGIN_UI_URL
      lifespan: 10m

    logout:
      after:
        default_browser_return_url: null # SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL

    registration:
      ui_url: null # SELFSERVICE_FLOWS_REGISTRATION_UI_URL
      lifespan: 10m
      after:
        hooks:
          - hook: web_hook
            config:
              url: null:// # SELFSERVICE_FLOWS_REGISTRATION_AFTER_HOOKS_0_CONFIG_URL
              method: POST
              body: file:///etc/ory-kratos/webhook-after-registration.jsonnet
              response:
                ignore: true

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: argon2

identity:
  default_schema_id: user_v0
  schemas:
    - id: user_v0
      url: file:///etc/ory-kratos/user-v0.schema.json

courier:
  smtp:
    connection_uri: null # COURIER_SMTP_CONNECTION_URI
    from_address: no-reply@lets.church
    from_name: Let's Church
