extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:solid/typescript'
parser: '@typescript-eslint/parser'
env:
  node: true
  browser: true
plugins:
  - solid
settings:
  import/resolver:
    typescript: true
    node: true
rules:
  import/order: error
