extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:astro/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - astro
settings:
  import/resolver:
    typescript: true
    node: true
rules:
  import/order: error
  import/no-unresolved: ['error', { ignore: ['^astro:'] }]
overrides:
  - files: ['*.astro']
    parser: 'astro-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.astro']
