---
- name: Install docker
  hosts: import-workers
  become: true
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Get the latest commit hash
      shell: git rev-parse HEAD | head -c 8
      register: lc_hash_result
      delegate_to: localhost
      changed_when: false

    - name: Set LC_HASH variable
      set_fact:
        LC_HASH: "{{ lc_hash_result.stdout }}"

    - name: Set identity variable to the remote hostname
      set_fact:
        IDENTITY: "{{ inventory_hostname }}"

    - name: Create app directory
      ansible.builtin.file:
        path: app
        state: directory
        mode: 744

    - name: Copy env file to remote host
      ansible.builtin.copy:
        src: ./templates/.crypt.env
        dest: app/.env
        mode: 644

    - name: Copy compose file to remote host
      ansible.builtin.template:
        src: ./templates/docker-compose.yml.j2
        dest: app/docker-compose.yml
        mode: 644
      vars:
        lc_hash: "{{ LC_HASH }}"
        identity: "{{ IDENTITY }}"
      notify:
        - docker-compose

  handlers:
    - name: docker-compose
      community.docker.docker_compose_v2:
        project_src: app
