default:
  @just --choose

init:
  ansible-galaxy install -r requirements.yml

play-docker:
  ansible-playbook ./playbooks/install-docker.yml -K
play-import-worker:
  ansible-playbook ./playbooks/import-worker.yml -K

play: play-docker play-import-worker
