/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as DashboardRouteImport } from './routes/dashboard_'
import { Route as AuthRouteImport } from './routes/auth_'
import { Route as MainRouteImport } from './routes/_main'
import { Route as DashboardIndexRouteImport } from './routes/dashboard_/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as TrpcSplatRouteImport } from './routes/trpc.$'
import { Route as OidcUserinfoRouteImport } from './routes/oidc.userinfo'
import { Route as OidcTokenRouteImport } from './routes/oidc.token'
import { Route as OidcLogoutRouteImport } from './routes/oidc.logout'
import { Route as OidcAuthorizeRouteImport } from './routes/oidc.authorize'
import { Route as MediaRssDotxmlRouteImport } from './routes/media.rss[.]xml'
import { Route as InvitationsInvalidRouteImport } from './routes/invitations_.invalid'
import { Route as InvitationsExpiredRouteImport } from './routes/invitations_.expired'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations_.accept'
import { Route as EmbedChurchesRouteImport } from './routes/embed.churches'
import { Route as DashboardOrganizationsRouteImport } from './routes/dashboard_/organizations'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard_/invitations'
import { Route as DashboardChurchesRouteImport } from './routes/dashboard_/churches'
import { Route as DashboardChannelsRouteImport } from './routes/dashboard_/channels'
import { Route as DashboardAdminRouteImport } from './routes/dashboard_/admin'
import { Route as DashboardAccountRouteImport } from './routes/dashboard_/account'
import { Route as AuthVerifyRouteImport } from './routes/auth_/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth_/register'
import { Route as AuthLogoutRouteImport } from './routes/auth_/logout'
import { Route as AuthLoginRouteImport } from './routes/auth_/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth_/forgot-password'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainLibraryRouteImport } from './routes/_main/library'
import { Route as MainHistoryRouteImport } from './routes/_main/history'
import { Route as MainFollowingRouteImport } from './routes/_main/following'
import { Route as MainChurchesRouteImport } from './routes/_main/churches'
import { Route as MainChannelsRouteImport } from './routes/_main/channels'
import { Route as MainAboutRouteImport } from './routes/_main.about'
import { Route as MainSlugRouteImport } from './routes/_main/$slug'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known.openid-configuration'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known.jwks[.]json'
import { Route as DashboardAdminReindexRouteImport } from './routes/dashboard_/admin_.reindex'
import { Route as MainAboutIndexRouteImport } from './routes/_main/about/index'
import { Route as SeriesSeriesIdRssDotxmlRouteImport } from './routes/series.$seriesId.rss[.]xml'
import { Route as PlaylistPlaylistIdRssDotxmlRouteImport } from './routes/playlist.$playlistId.rss[.]xml'
import { Route as EmbedMediaMediaIdRouteImport } from './routes/embed.media.$mediaId'
import { Route as EmbedChannelSlugRouteImport } from './routes/embed.channel.$slug'
import { Route as DashboardOrganizationsOrgIdRouteImport } from './routes/dashboard_/organizations_.$orgId'
import { Route as DashboardInvitationsAcceptRouteImport } from './routes/dashboard_/invitations_/accept'
import { Route as DashboardChurchesNewRouteImport } from './routes/dashboard_/churches_.new'
import { Route as DashboardChurchesChurchIdRouteImport } from './routes/dashboard_/churches_.$churchId'
import { Route as DashboardChannelsNewRouteImport } from './routes/dashboard_/channels_.new'
import { Route as DashboardChannelsChannelIdRouteImport } from './routes/dashboard_/channels_.$channelId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard_/admin_.users'
import { Route as DashboardAdminUploadBackupsRouteImport } from './routes/dashboard_/admin_.upload-backups'
import { Route as DashboardAdminStorageAuditRouteImport } from './routes/dashboard_/admin_.storage-audit'
import { Route as DashboardAdminSearchesRouteImport } from './routes/dashboard_/admin_/searches'
import { Route as DashboardAdminReprocessRouteImport } from './routes/dashboard_/admin_.reprocess'
import { Route as DashboardAdminProcessingUploadsRouteImport } from './routes/dashboard_/admin_.processing-uploads'
import { Route as DashboardAdminOrganizationsRouteImport } from './routes/dashboard_/admin_.organizations'
import { Route as DashboardAdminOrganizationTagsRouteImport } from './routes/dashboard_/admin_.organization-tags'
import { Route as DashboardAdminNewsletterListsRouteImport } from './routes/dashboard_/admin_.newsletter-lists'
import { Route as DashboardAdminMaintenanceRouteImport } from './routes/dashboard_/admin_/maintenance'
import { Route as DashboardAdminLlmEvalRouteImport } from './routes/dashboard_/admin_.llm-eval'
import { Route as DashboardAdminImportSourcesRouteImport } from './routes/dashboard_/admin_.import-sources'
import { Route as DashboardAdminFeaturedRouteImport } from './routes/dashboard_/admin_/featured'
import { Route as DashboardAdminFailedUploadsRouteImport } from './routes/dashboard_/admin_.failed-uploads'
import { Route as DashboardAdminFailedSummariesRouteImport } from './routes/dashboard_/admin_.failed-summaries'
import { Route as DashboardAdminFailedAnnotationsRouteImport } from './routes/dashboard_/admin_.failed-annotations'
import { Route as DashboardAdminDuplicateUploadsRouteImport } from './routes/dashboard_/admin_.duplicate-uploads'
import { Route as DashboardAdminDeletingUploadsRouteImport } from './routes/dashboard_/admin_.deleting-uploads'
import { Route as DashboardAdminChannelsRouteImport } from './routes/dashboard_/admin_.channels'
import { Route as DashboardAdminBackfillFilenamesRouteImport } from './routes/dashboard_/admin_.backfill-filenames'
import { Route as DashboardAccountSecurityRouteImport } from './routes/dashboard_/account_.security'
import { Route as DashboardAccountProfileRouteImport } from './routes/dashboard_/account_.profile'
import { Route as DashboardAccountNewsletterRouteImport } from './routes/dashboard_/account_.newsletter'
import { Route as ChannelSlugRssDotxmlRouteImport } from './routes/channel.$slug.rss[.]xml'
import { Route as ChannelSlugPodcastDotxmlRouteImport } from './routes/channel.$slug.podcast[.]xml'
import { Route as MainSeriesSeriesIdRouteImport } from './routes/_main/series.$seriesId'
import { Route as MainPlaylistPlaylistIdRouteImport } from './routes/_main/playlist.$playlistId'
import { Route as MainMediaMediaIdRouteImport } from './routes/_main/media/$mediaId'
import { Route as MainChurchesSlugRouteImport } from './routes/_main/churches_.$slug'
import { Route as MainChannelSlugRouteImport } from './routes/_main/channel.$slug'
import { Route as MainAboutTheologyRouteImport } from './routes/_main/about/theology'
import { Route as MainAboutTermsRouteImport } from './routes/_main/about/terms'
import { Route as MainAboutPrivacyRouteImport } from './routes/_main/about/privacy'
import { Route as MainAboutDoreanRouteImport } from './routes/_main/about/dorean'
import { Route as MainAboutDmcaRouteImport } from './routes/_main/about/dmca'
import { Route as MainAboutAddContentRouteImport } from './routes/_main/about/add-content'
import { Route as MainAboutAddChurchRouteImport } from './routes/_main/about/add-church'
import { Route as DashboardOrganizationsOrgIdMembersRouteImport } from './routes/dashboard_/organizations_.$orgId_.members'
import { Route as DashboardOrganizationsOrgIdEditRouteImport } from './routes/dashboard_/organizations_.$orgId_.edit'
import { Route as DashboardOrganizationsOrgIdAssociationsRouteImport } from './routes/dashboard_/organizations_.$orgId_.associations'
import { Route as DashboardChurchesChurchIdMembersRouteImport } from './routes/dashboard_/churches_.$churchId_.members'
import { Route as DashboardChurchesChurchIdLeadersRouteImport } from './routes/dashboard_/churches_.$churchId_.leaders'
import { Route as DashboardChurchesChurchIdEditRouteImport } from './routes/dashboard_/churches_.$churchId_.edit'
import { Route as DashboardChurchesChurchIdChannelsRouteImport } from './routes/dashboard_/churches_.$churchId_.channels'
import { Route as DashboardChannelsChannelIdUploadsRouteImport } from './routes/dashboard_/channels_.$channelId_.uploads'
import { Route as DashboardChannelsChannelIdPlaylistsRouteImport } from './routes/dashboard_/channels_.$channelId_.playlists'
import { Route as DashboardChannelsChannelIdMembersRouteImport } from './routes/dashboard_/channels_.$channelId_.members'
import { Route as DashboardChannelsChannelIdEditRouteImport } from './routes/dashboard_/channels_.$channelId_.edit'
import { Route as DashboardChannelsChannelIdUploadsUploadIdRouteImport } from './routes/dashboard_/channels_.$channelId_.uploads_.$uploadId'
import { Route as DashboardChannelsChannelIdPlaylistsPlaylistIdRouteImport } from './routes/dashboard_/channels_.$channelId_.playlists_.$playlistId'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard_',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth_',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const TrpcSplatRoute = TrpcSplatRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcUserinfoRoute = OidcUserinfoRouteImport.update({
  id: '/oidc/userinfo',
  path: '/oidc/userinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcTokenRoute = OidcTokenRouteImport.update({
  id: '/oidc/token',
  path: '/oidc/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcLogoutRoute = OidcLogoutRouteImport.update({
  id: '/oidc/logout',
  path: '/oidc/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcAuthorizeRoute = OidcAuthorizeRouteImport.update({
  id: '/oidc/authorize',
  path: '/oidc/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRssDotxmlRoute = MediaRssDotxmlRouteImport.update({
  id: '/media/rss.xml',
  path: '/media/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsInvalidRoute = InvitationsInvalidRouteImport.update({
  id: '/invitations_/invalid',
  path: '/invitations/invalid',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsExpiredRoute = InvitationsExpiredRouteImport.update({
  id: '/invitations_/expired',
  path: '/invitations/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations_/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedChurchesRoute = EmbedChurchesRouteImport.update({
  id: '/embed/churches',
  path: '/embed/churches',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationsRoute = DashboardOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChurchesRoute = DashboardChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainLibraryRoute = MainLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MainRoute,
} as any)
const MainHistoryRoute = MainHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MainRoute,
} as any)
const MainFollowingRoute = MainFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MainRoute,
} as any)
const MainChurchesRoute = MainChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => MainRoute,
} as any)
const MainChannelsRoute = MainChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainSlugRoute = MainSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MainRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminReindexRoute = DashboardAdminReindexRouteImport.update({
  id: '/admin_/reindex',
  path: '/admin/reindex',
  getParentRoute: () => DashboardRoute,
} as any)
const MainAboutIndexRoute = MainAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAboutRoute,
} as any)
const SeriesSeriesIdRssDotxmlRoute = SeriesSeriesIdRssDotxmlRouteImport.update({
  id: '/series/$seriesId/rss.xml',
  path: '/series/$seriesId/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRssDotxmlRoute =
  PlaylistPlaylistIdRssDotxmlRouteImport.update({
    id: '/playlist/$playlistId/rss.xml',
    path: '/playlist/$playlistId/rss.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmbedMediaMediaIdRoute = EmbedMediaMediaIdRouteImport.update({
  id: '/embed/media/$mediaId',
  path: '/embed/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedChannelSlugRoute = EmbedChannelSlugRouteImport.update({
  id: '/embed/channel/$slug',
  path: '/embed/channel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationsOrgIdRoute =
  DashboardOrganizationsOrgIdRouteImport.update({
    id: '/organizations_/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInvitationsAcceptRoute =
  DashboardInvitationsAcceptRouteImport.update({
    id: '/invitations_/accept',
    path: '/invitations/accept',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesNewRoute = DashboardChurchesNewRouteImport.update({
  id: '/churches_/new',
  path: '/churches/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChurchesChurchIdRoute =
  DashboardChurchesChurchIdRouteImport.update({
    id: '/churches_/$churchId',
    path: '/churches/$churchId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsNewRoute = DashboardChannelsNewRouteImport.update({
  id: '/channels_/new',
  path: '/channels/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsChannelIdRoute =
  DashboardChannelsChannelIdRouteImport.update({
    id: '/channels_/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUploadBackupsRoute =
  DashboardAdminUploadBackupsRouteImport.update({
    id: '/admin_/upload-backups',
    path: '/admin/upload-backups',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStorageAuditRoute =
  DashboardAdminStorageAuditRouteImport.update({
    id: '/admin_/storage-audit',
    path: '/admin/storage-audit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSearchesRoute = DashboardAdminSearchesRouteImport.update({
  id: '/admin_/searches',
  path: '/admin/searches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminReprocessRoute = DashboardAdminReprocessRouteImport.update({
  id: '/admin_/reprocess',
  path: '/admin/reprocess',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminProcessingUploadsRoute =
  DashboardAdminProcessingUploadsRouteImport.update({
    id: '/admin_/processing-uploads',
    path: '/admin/processing-uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOrganizationsRoute =
  DashboardAdminOrganizationsRouteImport.update({
    id: '/admin_/organizations',
    path: '/admin/organizations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOrganizationTagsRoute =
  DashboardAdminOrganizationTagsRouteImport.update({
    id: '/admin_/organization-tags',
    path: '/admin/organization-tags',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminNewsletterListsRoute =
  DashboardAdminNewsletterListsRouteImport.update({
    id: '/admin_/newsletter-lists',
    path: '/admin/newsletter-lists',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminMaintenanceRoute =
  DashboardAdminMaintenanceRouteImport.update({
    id: '/admin_/maintenance',
    path: '/admin/maintenance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminLlmEvalRoute = DashboardAdminLlmEvalRouteImport.update({
  id: '/admin_/llm-eval',
  path: '/admin/llm-eval',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminImportSourcesRoute =
  DashboardAdminImportSourcesRouteImport.update({
    id: '/admin_/import-sources',
    path: '/admin/import-sources',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminFeaturedRoute = DashboardAdminFeaturedRouteImport.update({
  id: '/admin_/featured',
  path: '/admin/featured',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminFailedUploadsRoute =
  DashboardAdminFailedUploadsRouteImport.update({
    id: '/admin_/failed-uploads',
    path: '/admin/failed-uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminFailedSummariesRoute =
  DashboardAdminFailedSummariesRouteImport.update({
    id: '/admin_/failed-summaries',
    path: '/admin/failed-summaries',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminFailedAnnotationsRoute =
  DashboardAdminFailedAnnotationsRouteImport.update({
    id: '/admin_/failed-annotations',
    path: '/admin/failed-annotations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminDuplicateUploadsRoute =
  DashboardAdminDuplicateUploadsRouteImport.update({
    id: '/admin_/duplicate-uploads',
    path: '/admin/duplicate-uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminDeletingUploadsRoute =
  DashboardAdminDeletingUploadsRouteImport.update({
    id: '/admin_/deleting-uploads',
    path: '/admin/deleting-uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminChannelsRoute = DashboardAdminChannelsRouteImport.update({
  id: '/admin_/channels',
  path: '/admin/channels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminBackfillFilenamesRoute =
  DashboardAdminBackfillFilenamesRouteImport.update({
    id: '/admin_/backfill-filenames',
    path: '/admin/backfill-filenames',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountSecurityRoute =
  DashboardAccountSecurityRouteImport.update({
    id: '/account_/security',
    path: '/account/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountProfileRoute = DashboardAccountProfileRouteImport.update({
  id: '/account_/profile',
  path: '/account/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountNewsletterRoute =
  DashboardAccountNewsletterRouteImport.update({
    id: '/account_/newsletter',
    path: '/account/newsletter',
    getParentRoute: () => DashboardRoute,
  } as any)
const ChannelSlugRssDotxmlRoute = ChannelSlugRssDotxmlRouteImport.update({
  id: '/channel/$slug/rss.xml',
  path: '/channel/$slug/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelSlugPodcastDotxmlRoute =
  ChannelSlugPodcastDotxmlRouteImport.update({
    id: '/channel/$slug/podcast.xml',
    path: '/channel/$slug/podcast.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainSeriesSeriesIdRoute = MainSeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => MainRoute,
} as any)
const MainPlaylistPlaylistIdRoute = MainPlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => MainRoute,
} as any)
const MainMediaMediaIdRoute = MainMediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => MainRoute,
} as any)
const MainChurchesSlugRoute = MainChurchesSlugRouteImport.update({
  id: '/churches_/$slug',
  path: '/churches/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainChannelSlugRoute = MainChannelSlugRouteImport.update({
  id: '/channel/$slug',
  path: '/channel/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutTheologyRoute = MainAboutTheologyRouteImport.update({
  id: '/theology',
  path: '/theology',
  getParentRoute: () => MainAboutRoute,
} as any)
const MainAboutTermsRoute = MainAboutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainAboutRoute,
} as any)
const MainAboutPrivacyRoute = MainAboutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainAboutRoute,
} as any)
const MainAboutDoreanRoute = MainAboutDoreanRouteImport.update({
  id: '/dorean',
  path: '/dorean',
  getParentRoute: () => MainAboutRoute,
} as any)
const MainAboutDmcaRoute = MainAboutDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => MainAboutRoute,
} as any)
const MainAboutAddContentRoute = MainAboutAddContentRouteImport.update({
  id: '/add-content',
  path: '/add-content',
  getParentRoute: () => MainAboutRoute,
} as any)
const MainAboutAddChurchRoute = MainAboutAddChurchRouteImport.update({
  id: '/add-church',
  path: '/add-church',
  getParentRoute: () => MainAboutRoute,
} as any)
const DashboardOrganizationsOrgIdMembersRoute =
  DashboardOrganizationsOrgIdMembersRouteImport.update({
    id: '/organizations_/$orgId_/members',
    path: '/organizations/$orgId/members',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationsOrgIdEditRoute =
  DashboardOrganizationsOrgIdEditRouteImport.update({
    id: '/organizations_/$orgId_/edit',
    path: '/organizations/$orgId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationsOrgIdAssociationsRoute =
  DashboardOrganizationsOrgIdAssociationsRouteImport.update({
    id: '/organizations_/$orgId_/associations',
    path: '/organizations/$orgId/associations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdMembersRoute =
  DashboardChurchesChurchIdMembersRouteImport.update({
    id: '/churches_/$churchId_/members',
    path: '/churches/$churchId/members',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdLeadersRoute =
  DashboardChurchesChurchIdLeadersRouteImport.update({
    id: '/churches_/$churchId_/leaders',
    path: '/churches/$churchId/leaders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdEditRoute =
  DashboardChurchesChurchIdEditRouteImport.update({
    id: '/churches_/$churchId_/edit',
    path: '/churches/$churchId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdChannelsRoute =
  DashboardChurchesChurchIdChannelsRouteImport.update({
    id: '/churches_/$churchId_/channels',
    path: '/churches/$churchId/channels',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdUploadsRoute =
  DashboardChannelsChannelIdUploadsRouteImport.update({
    id: '/channels_/$channelId_/uploads',
    path: '/channels/$channelId/uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdPlaylistsRoute =
  DashboardChannelsChannelIdPlaylistsRouteImport.update({
    id: '/channels_/$channelId_/playlists',
    path: '/channels/$channelId/playlists',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdMembersRoute =
  DashboardChannelsChannelIdMembersRouteImport.update({
    id: '/channels_/$channelId_/members',
    path: '/channels/$channelId/members',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdEditRoute =
  DashboardChannelsChannelIdEditRouteImport.update({
    id: '/channels_/$channelId_/edit',
    path: '/channels/$channelId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdUploadsUploadIdRoute =
  DashboardChannelsChannelIdUploadsUploadIdRouteImport.update({
    id: '/channels_/$channelId_/uploads_/$uploadId',
    path: '/channels/$channelId/uploads/$uploadId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdPlaylistsPlaylistIdRoute =
  DashboardChannelsChannelIdPlaylistsPlaylistIdRouteImport.update({
    id: '/channels_/$channelId_/playlists_/$playlistId',
    path: '/channels/$channelId/playlists/$playlistId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$slug': typeof MainSlugRoute
  '/about': typeof MainAboutRouteWithChildren
  '/channels': typeof MainChannelsRoute
  '/churches': typeof MainChurchesRoute
  '/following': typeof MainFollowingRoute
  '/history': typeof MainHistoryRoute
  '/library': typeof MainLibraryRoute
  '/search': typeof MainSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/churches': typeof DashboardChurchesRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/embed/churches': typeof EmbedChurchesRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/invitations/expired': typeof InvitationsExpiredRoute
  '/invitations/invalid': typeof InvitationsInvalidRoute
  '/media/rss.xml': typeof MediaRssDotxmlRoute
  '/oidc/authorize': typeof OidcAuthorizeRoute
  '/oidc/logout': typeof OidcLogoutRoute
  '/oidc/token': typeof OidcTokenRoute
  '/oidc/userinfo': typeof OidcUserinfoRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/': typeof MainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/about/add-church': typeof MainAboutAddChurchRoute
  '/about/add-content': typeof MainAboutAddContentRoute
  '/about/dmca': typeof MainAboutDmcaRoute
  '/about/dorean': typeof MainAboutDoreanRoute
  '/about/privacy': typeof MainAboutPrivacyRoute
  '/about/terms': typeof MainAboutTermsRoute
  '/about/theology': typeof MainAboutTheologyRoute
  '/channel/$slug': typeof MainChannelSlugRoute
  '/churches/$slug': typeof MainChurchesSlugRoute
  '/media/$mediaId': typeof MainMediaMediaIdRoute
  '/playlist/$playlistId': typeof MainPlaylistPlaylistIdRoute
  '/series/$seriesId': typeof MainSeriesSeriesIdRoute
  '/channel/$slug/podcast.xml': typeof ChannelSlugPodcastDotxmlRoute
  '/channel/$slug/rss.xml': typeof ChannelSlugRssDotxmlRoute
  '/dashboard/account/newsletter': typeof DashboardAccountNewsletterRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/security': typeof DashboardAccountSecurityRoute
  '/dashboard/admin/backfill-filenames': typeof DashboardAdminBackfillFilenamesRoute
  '/dashboard/admin/channels': typeof DashboardAdminChannelsRoute
  '/dashboard/admin/deleting-uploads': typeof DashboardAdminDeletingUploadsRoute
  '/dashboard/admin/duplicate-uploads': typeof DashboardAdminDuplicateUploadsRoute
  '/dashboard/admin/failed-annotations': typeof DashboardAdminFailedAnnotationsRoute
  '/dashboard/admin/failed-summaries': typeof DashboardAdminFailedSummariesRoute
  '/dashboard/admin/failed-uploads': typeof DashboardAdminFailedUploadsRoute
  '/dashboard/admin/featured': typeof DashboardAdminFeaturedRoute
  '/dashboard/admin/import-sources': typeof DashboardAdminImportSourcesRoute
  '/dashboard/admin/llm-eval': typeof DashboardAdminLlmEvalRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/newsletter-lists': typeof DashboardAdminNewsletterListsRoute
  '/dashboard/admin/organization-tags': typeof DashboardAdminOrganizationTagsRoute
  '/dashboard/admin/organizations': typeof DashboardAdminOrganizationsRoute
  '/dashboard/admin/processing-uploads': typeof DashboardAdminProcessingUploadsRoute
  '/dashboard/admin/reindex': typeof DashboardAdminReindexRoute
  '/dashboard/admin/reprocess': typeof DashboardAdminReprocessRoute
  '/dashboard/admin/searches': typeof DashboardAdminSearchesRoute
  '/dashboard/admin/storage-audit': typeof DashboardAdminStorageAuditRoute
  '/dashboard/admin/upload-backups': typeof DashboardAdminUploadBackupsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/channels/new': typeof DashboardChannelsNewRoute
  '/dashboard/churches/$churchId': typeof DashboardChurchesChurchIdRoute
  '/dashboard/churches/new': typeof DashboardChurchesNewRoute
  '/dashboard/invitations/accept': typeof DashboardInvitationsAcceptRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/embed/channel/$slug': typeof EmbedChannelSlugRoute
  '/embed/media/$mediaId': typeof EmbedMediaMediaIdRoute
  '/playlist/$playlistId/rss.xml': typeof PlaylistPlaylistIdRssDotxmlRoute
  '/series/$seriesId/rss.xml': typeof SeriesSeriesIdRssDotxmlRoute
  '/about/': typeof MainAboutIndexRoute
  '/dashboard/channels/$channelId/edit': typeof DashboardChannelsChannelIdEditRoute
  '/dashboard/channels/$channelId/members': typeof DashboardChannelsChannelIdMembersRoute
  '/dashboard/channels/$channelId/playlists': typeof DashboardChannelsChannelIdPlaylistsRoute
  '/dashboard/channels/$channelId/uploads': typeof DashboardChannelsChannelIdUploadsRoute
  '/dashboard/churches/$churchId/channels': typeof DashboardChurchesChurchIdChannelsRoute
  '/dashboard/churches/$churchId/edit': typeof DashboardChurchesChurchIdEditRoute
  '/dashboard/churches/$churchId/leaders': typeof DashboardChurchesChurchIdLeadersRoute
  '/dashboard/churches/$churchId/members': typeof DashboardChurchesChurchIdMembersRoute
  '/dashboard/organizations/$orgId/associations': typeof DashboardOrganizationsOrgIdAssociationsRoute
  '/dashboard/organizations/$orgId/edit': typeof DashboardOrganizationsOrgIdEditRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/channels/$channelId/playlists/$playlistId': typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  '/dashboard/channels/$channelId/uploads/$uploadId': typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$slug': typeof MainSlugRoute
  '/channels': typeof MainChannelsRoute
  '/churches': typeof MainChurchesRoute
  '/following': typeof MainFollowingRoute
  '/history': typeof MainHistoryRoute
  '/library': typeof MainLibraryRoute
  '/search': typeof MainSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/churches': typeof DashboardChurchesRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/embed/churches': typeof EmbedChurchesRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/invitations/expired': typeof InvitationsExpiredRoute
  '/invitations/invalid': typeof InvitationsInvalidRoute
  '/media/rss.xml': typeof MediaRssDotxmlRoute
  '/oidc/authorize': typeof OidcAuthorizeRoute
  '/oidc/logout': typeof OidcLogoutRoute
  '/oidc/token': typeof OidcTokenRoute
  '/oidc/userinfo': typeof OidcUserinfoRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/about/add-church': typeof MainAboutAddChurchRoute
  '/about/add-content': typeof MainAboutAddContentRoute
  '/about/dmca': typeof MainAboutDmcaRoute
  '/about/dorean': typeof MainAboutDoreanRoute
  '/about/privacy': typeof MainAboutPrivacyRoute
  '/about/terms': typeof MainAboutTermsRoute
  '/about/theology': typeof MainAboutTheologyRoute
  '/channel/$slug': typeof MainChannelSlugRoute
  '/churches/$slug': typeof MainChurchesSlugRoute
  '/media/$mediaId': typeof MainMediaMediaIdRoute
  '/playlist/$playlistId': typeof MainPlaylistPlaylistIdRoute
  '/series/$seriesId': typeof MainSeriesSeriesIdRoute
  '/channel/$slug/podcast.xml': typeof ChannelSlugPodcastDotxmlRoute
  '/channel/$slug/rss.xml': typeof ChannelSlugRssDotxmlRoute
  '/dashboard/account/newsletter': typeof DashboardAccountNewsletterRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/security': typeof DashboardAccountSecurityRoute
  '/dashboard/admin/backfill-filenames': typeof DashboardAdminBackfillFilenamesRoute
  '/dashboard/admin/channels': typeof DashboardAdminChannelsRoute
  '/dashboard/admin/deleting-uploads': typeof DashboardAdminDeletingUploadsRoute
  '/dashboard/admin/duplicate-uploads': typeof DashboardAdminDuplicateUploadsRoute
  '/dashboard/admin/failed-annotations': typeof DashboardAdminFailedAnnotationsRoute
  '/dashboard/admin/failed-summaries': typeof DashboardAdminFailedSummariesRoute
  '/dashboard/admin/failed-uploads': typeof DashboardAdminFailedUploadsRoute
  '/dashboard/admin/featured': typeof DashboardAdminFeaturedRoute
  '/dashboard/admin/import-sources': typeof DashboardAdminImportSourcesRoute
  '/dashboard/admin/llm-eval': typeof DashboardAdminLlmEvalRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/newsletter-lists': typeof DashboardAdminNewsletterListsRoute
  '/dashboard/admin/organization-tags': typeof DashboardAdminOrganizationTagsRoute
  '/dashboard/admin/organizations': typeof DashboardAdminOrganizationsRoute
  '/dashboard/admin/processing-uploads': typeof DashboardAdminProcessingUploadsRoute
  '/dashboard/admin/reindex': typeof DashboardAdminReindexRoute
  '/dashboard/admin/reprocess': typeof DashboardAdminReprocessRoute
  '/dashboard/admin/searches': typeof DashboardAdminSearchesRoute
  '/dashboard/admin/storage-audit': typeof DashboardAdminStorageAuditRoute
  '/dashboard/admin/upload-backups': typeof DashboardAdminUploadBackupsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/channels/new': typeof DashboardChannelsNewRoute
  '/dashboard/churches/$churchId': typeof DashboardChurchesChurchIdRoute
  '/dashboard/churches/new': typeof DashboardChurchesNewRoute
  '/dashboard/invitations/accept': typeof DashboardInvitationsAcceptRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/embed/channel/$slug': typeof EmbedChannelSlugRoute
  '/embed/media/$mediaId': typeof EmbedMediaMediaIdRoute
  '/playlist/$playlistId/rss.xml': typeof PlaylistPlaylistIdRssDotxmlRoute
  '/series/$seriesId/rss.xml': typeof SeriesSeriesIdRssDotxmlRoute
  '/about': typeof MainAboutIndexRoute
  '/dashboard/channels/$channelId/edit': typeof DashboardChannelsChannelIdEditRoute
  '/dashboard/channels/$channelId/members': typeof DashboardChannelsChannelIdMembersRoute
  '/dashboard/channels/$channelId/playlists': typeof DashboardChannelsChannelIdPlaylistsRoute
  '/dashboard/channels/$channelId/uploads': typeof DashboardChannelsChannelIdUploadsRoute
  '/dashboard/churches/$churchId/channels': typeof DashboardChurchesChurchIdChannelsRoute
  '/dashboard/churches/$churchId/edit': typeof DashboardChurchesChurchIdEditRoute
  '/dashboard/churches/$churchId/leaders': typeof DashboardChurchesChurchIdLeadersRoute
  '/dashboard/churches/$churchId/members': typeof DashboardChurchesChurchIdMembersRoute
  '/dashboard/organizations/$orgId/associations': typeof DashboardOrganizationsOrgIdAssociationsRoute
  '/dashboard/organizations/$orgId/edit': typeof DashboardOrganizationsOrgIdEditRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/channels/$channelId/playlists/$playlistId': typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  '/dashboard/channels/$channelId/uploads/$uploadId': typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/auth_': typeof AuthRouteWithChildren
  '/dashboard_': typeof DashboardRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_main/$slug': typeof MainSlugRoute
  '/_main/about': typeof MainAboutRouteWithChildren
  '/_main/channels': typeof MainChannelsRoute
  '/_main/churches': typeof MainChurchesRoute
  '/_main/following': typeof MainFollowingRoute
  '/_main/history': typeof MainHistoryRoute
  '/_main/library': typeof MainLibraryRoute
  '/_main/search': typeof MainSearchRoute
  '/auth_/forgot-password': typeof AuthForgotPasswordRoute
  '/auth_/login': typeof AuthLoginRoute
  '/auth_/logout': typeof AuthLogoutRoute
  '/auth_/register': typeof AuthRegisterRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/auth_/verify': typeof AuthVerifyRoute
  '/dashboard_/account': typeof DashboardAccountRoute
  '/dashboard_/admin': typeof DashboardAdminRoute
  '/dashboard_/channels': typeof DashboardChannelsRoute
  '/dashboard_/churches': typeof DashboardChurchesRoute
  '/dashboard_/invitations': typeof DashboardInvitationsRoute
  '/dashboard_/organizations': typeof DashboardOrganizationsRoute
  '/embed/churches': typeof EmbedChurchesRoute
  '/invitations_/accept': typeof InvitationsAcceptRoute
  '/invitations_/expired': typeof InvitationsExpiredRoute
  '/invitations_/invalid': typeof InvitationsInvalidRoute
  '/media/rss.xml': typeof MediaRssDotxmlRoute
  '/oidc/authorize': typeof OidcAuthorizeRoute
  '/oidc/logout': typeof OidcLogoutRoute
  '/oidc/token': typeof OidcTokenRoute
  '/oidc/userinfo': typeof OidcUserinfoRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/_main/': typeof MainIndexRoute
  '/dashboard_/': typeof DashboardIndexRoute
  '/_main/about/add-church': typeof MainAboutAddChurchRoute
  '/_main/about/add-content': typeof MainAboutAddContentRoute
  '/_main/about/dmca': typeof MainAboutDmcaRoute
  '/_main/about/dorean': typeof MainAboutDoreanRoute
  '/_main/about/privacy': typeof MainAboutPrivacyRoute
  '/_main/about/terms': typeof MainAboutTermsRoute
  '/_main/about/theology': typeof MainAboutTheologyRoute
  '/_main/channel/$slug': typeof MainChannelSlugRoute
  '/_main/churches_/$slug': typeof MainChurchesSlugRoute
  '/_main/media/$mediaId': typeof MainMediaMediaIdRoute
  '/_main/playlist/$playlistId': typeof MainPlaylistPlaylistIdRoute
  '/_main/series/$seriesId': typeof MainSeriesSeriesIdRoute
  '/channel/$slug/podcast.xml': typeof ChannelSlugPodcastDotxmlRoute
  '/channel/$slug/rss.xml': typeof ChannelSlugRssDotxmlRoute
  '/dashboard_/account_/newsletter': typeof DashboardAccountNewsletterRoute
  '/dashboard_/account_/profile': typeof DashboardAccountProfileRoute
  '/dashboard_/account_/security': typeof DashboardAccountSecurityRoute
  '/dashboard_/admin_/backfill-filenames': typeof DashboardAdminBackfillFilenamesRoute
  '/dashboard_/admin_/channels': typeof DashboardAdminChannelsRoute
  '/dashboard_/admin_/deleting-uploads': typeof DashboardAdminDeletingUploadsRoute
  '/dashboard_/admin_/duplicate-uploads': typeof DashboardAdminDuplicateUploadsRoute
  '/dashboard_/admin_/failed-annotations': typeof DashboardAdminFailedAnnotationsRoute
  '/dashboard_/admin_/failed-summaries': typeof DashboardAdminFailedSummariesRoute
  '/dashboard_/admin_/failed-uploads': typeof DashboardAdminFailedUploadsRoute
  '/dashboard_/admin_/featured': typeof DashboardAdminFeaturedRoute
  '/dashboard_/admin_/import-sources': typeof DashboardAdminImportSourcesRoute
  '/dashboard_/admin_/llm-eval': typeof DashboardAdminLlmEvalRoute
  '/dashboard_/admin_/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard_/admin_/newsletter-lists': typeof DashboardAdminNewsletterListsRoute
  '/dashboard_/admin_/organization-tags': typeof DashboardAdminOrganizationTagsRoute
  '/dashboard_/admin_/organizations': typeof DashboardAdminOrganizationsRoute
  '/dashboard_/admin_/processing-uploads': typeof DashboardAdminProcessingUploadsRoute
  '/dashboard_/admin_/reindex': typeof DashboardAdminReindexRoute
  '/dashboard_/admin_/reprocess': typeof DashboardAdminReprocessRoute
  '/dashboard_/admin_/searches': typeof DashboardAdminSearchesRoute
  '/dashboard_/admin_/storage-audit': typeof DashboardAdminStorageAuditRoute
  '/dashboard_/admin_/upload-backups': typeof DashboardAdminUploadBackupsRoute
  '/dashboard_/admin_/users': typeof DashboardAdminUsersRoute
  '/dashboard_/channels_/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard_/channels_/new': typeof DashboardChannelsNewRoute
  '/dashboard_/churches_/$churchId': typeof DashboardChurchesChurchIdRoute
  '/dashboard_/churches_/new': typeof DashboardChurchesNewRoute
  '/dashboard_/invitations_/accept': typeof DashboardInvitationsAcceptRoute
  '/dashboard_/organizations_/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/embed/channel/$slug': typeof EmbedChannelSlugRoute
  '/embed/media/$mediaId': typeof EmbedMediaMediaIdRoute
  '/playlist/$playlistId/rss.xml': typeof PlaylistPlaylistIdRssDotxmlRoute
  '/series/$seriesId/rss.xml': typeof SeriesSeriesIdRssDotxmlRoute
  '/_main/about/': typeof MainAboutIndexRoute
  '/dashboard_/channels_/$channelId_/edit': typeof DashboardChannelsChannelIdEditRoute
  '/dashboard_/channels_/$channelId_/members': typeof DashboardChannelsChannelIdMembersRoute
  '/dashboard_/channels_/$channelId_/playlists': typeof DashboardChannelsChannelIdPlaylistsRoute
  '/dashboard_/channels_/$channelId_/uploads': typeof DashboardChannelsChannelIdUploadsRoute
  '/dashboard_/churches_/$churchId_/channels': typeof DashboardChurchesChurchIdChannelsRoute
  '/dashboard_/churches_/$churchId_/edit': typeof DashboardChurchesChurchIdEditRoute
  '/dashboard_/churches_/$churchId_/leaders': typeof DashboardChurchesChurchIdLeadersRoute
  '/dashboard_/churches_/$churchId_/members': typeof DashboardChurchesChurchIdMembersRoute
  '/dashboard_/organizations_/$orgId_/associations': typeof DashboardOrganizationsOrgIdAssociationsRoute
  '/dashboard_/organizations_/$orgId_/edit': typeof DashboardOrganizationsOrgIdEditRoute
  '/dashboard_/organizations_/$orgId_/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard_/channels_/$channelId_/playlists_/$playlistId': typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  '/dashboard_/channels_/$channelId_/uploads_/$uploadId': typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/maintenance'
    | '/.well-known/jwks.json'
    | '/.well-known/openid-configuration'
    | '/$slug'
    | '/about'
    | '/channels'
    | '/churches'
    | '/following'
    | '/history'
    | '/library'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/channels'
    | '/dashboard/churches'
    | '/dashboard/invitations'
    | '/dashboard/organizations'
    | '/embed/churches'
    | '/invitations/accept'
    | '/invitations/expired'
    | '/invitations/invalid'
    | '/media/rss.xml'
    | '/oidc/authorize'
    | '/oidc/logout'
    | '/oidc/token'
    | '/oidc/userinfo'
    | '/trpc/$'
    | '/'
    | '/dashboard/'
    | '/about/add-church'
    | '/about/add-content'
    | '/about/dmca'
    | '/about/dorean'
    | '/about/privacy'
    | '/about/terms'
    | '/about/theology'
    | '/channel/$slug'
    | '/churches/$slug'
    | '/media/$mediaId'
    | '/playlist/$playlistId'
    | '/series/$seriesId'
    | '/channel/$slug/podcast.xml'
    | '/channel/$slug/rss.xml'
    | '/dashboard/account/newsletter'
    | '/dashboard/account/profile'
    | '/dashboard/account/security'
    | '/dashboard/admin/backfill-filenames'
    | '/dashboard/admin/channels'
    | '/dashboard/admin/deleting-uploads'
    | '/dashboard/admin/duplicate-uploads'
    | '/dashboard/admin/failed-annotations'
    | '/dashboard/admin/failed-summaries'
    | '/dashboard/admin/failed-uploads'
    | '/dashboard/admin/featured'
    | '/dashboard/admin/import-sources'
    | '/dashboard/admin/llm-eval'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/newsletter-lists'
    | '/dashboard/admin/organization-tags'
    | '/dashboard/admin/organizations'
    | '/dashboard/admin/processing-uploads'
    | '/dashboard/admin/reindex'
    | '/dashboard/admin/reprocess'
    | '/dashboard/admin/searches'
    | '/dashboard/admin/storage-audit'
    | '/dashboard/admin/upload-backups'
    | '/dashboard/admin/users'
    | '/dashboard/channels/$channelId'
    | '/dashboard/channels/new'
    | '/dashboard/churches/$churchId'
    | '/dashboard/churches/new'
    | '/dashboard/invitations/accept'
    | '/dashboard/organizations/$orgId'
    | '/embed/channel/$slug'
    | '/embed/media/$mediaId'
    | '/playlist/$playlistId/rss.xml'
    | '/series/$seriesId/rss.xml'
    | '/about/'
    | '/dashboard/channels/$channelId/edit'
    | '/dashboard/channels/$channelId/members'
    | '/dashboard/channels/$channelId/playlists'
    | '/dashboard/channels/$channelId/uploads'
    | '/dashboard/churches/$churchId/channels'
    | '/dashboard/churches/$churchId/edit'
    | '/dashboard/churches/$churchId/leaders'
    | '/dashboard/churches/$churchId/members'
    | '/dashboard/organizations/$orgId/associations'
    | '/dashboard/organizations/$orgId/edit'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/channels/$channelId/playlists/$playlistId'
    | '/dashboard/channels/$channelId/uploads/$uploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/maintenance'
    | '/.well-known/jwks.json'
    | '/.well-known/openid-configuration'
    | '/$slug'
    | '/channels'
    | '/churches'
    | '/following'
    | '/history'
    | '/library'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/channels'
    | '/dashboard/churches'
    | '/dashboard/invitations'
    | '/dashboard/organizations'
    | '/embed/churches'
    | '/invitations/accept'
    | '/invitations/expired'
    | '/invitations/invalid'
    | '/media/rss.xml'
    | '/oidc/authorize'
    | '/oidc/logout'
    | '/oidc/token'
    | '/oidc/userinfo'
    | '/trpc/$'
    | '/'
    | '/dashboard'
    | '/about/add-church'
    | '/about/add-content'
    | '/about/dmca'
    | '/about/dorean'
    | '/about/privacy'
    | '/about/terms'
    | '/about/theology'
    | '/channel/$slug'
    | '/churches/$slug'
    | '/media/$mediaId'
    | '/playlist/$playlistId'
    | '/series/$seriesId'
    | '/channel/$slug/podcast.xml'
    | '/channel/$slug/rss.xml'
    | '/dashboard/account/newsletter'
    | '/dashboard/account/profile'
    | '/dashboard/account/security'
    | '/dashboard/admin/backfill-filenames'
    | '/dashboard/admin/channels'
    | '/dashboard/admin/deleting-uploads'
    | '/dashboard/admin/duplicate-uploads'
    | '/dashboard/admin/failed-annotations'
    | '/dashboard/admin/failed-summaries'
    | '/dashboard/admin/failed-uploads'
    | '/dashboard/admin/featured'
    | '/dashboard/admin/import-sources'
    | '/dashboard/admin/llm-eval'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/newsletter-lists'
    | '/dashboard/admin/organization-tags'
    | '/dashboard/admin/organizations'
    | '/dashboard/admin/processing-uploads'
    | '/dashboard/admin/reindex'
    | '/dashboard/admin/reprocess'
    | '/dashboard/admin/searches'
    | '/dashboard/admin/storage-audit'
    | '/dashboard/admin/upload-backups'
    | '/dashboard/admin/users'
    | '/dashboard/channels/$channelId'
    | '/dashboard/channels/new'
    | '/dashboard/churches/$churchId'
    | '/dashboard/churches/new'
    | '/dashboard/invitations/accept'
    | '/dashboard/organizations/$orgId'
    | '/embed/channel/$slug'
    | '/embed/media/$mediaId'
    | '/playlist/$playlistId/rss.xml'
    | '/series/$seriesId/rss.xml'
    | '/about'
    | '/dashboard/channels/$channelId/edit'
    | '/dashboard/channels/$channelId/members'
    | '/dashboard/channels/$channelId/playlists'
    | '/dashboard/channels/$channelId/uploads'
    | '/dashboard/churches/$churchId/channels'
    | '/dashboard/churches/$churchId/edit'
    | '/dashboard/churches/$churchId/leaders'
    | '/dashboard/churches/$churchId/members'
    | '/dashboard/organizations/$orgId/associations'
    | '/dashboard/organizations/$orgId/edit'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/channels/$channelId/playlists/$playlistId'
    | '/dashboard/channels/$channelId/uploads/$uploadId'
  id:
    | '__root__'
    | '/_main'
    | '/auth_'
    | '/dashboard_'
    | '/maintenance'
    | '/.well-known/jwks.json'
    | '/.well-known/openid-configuration'
    | '/_main/$slug'
    | '/_main/about'
    | '/_main/channels'
    | '/_main/churches'
    | '/_main/following'
    | '/_main/history'
    | '/_main/library'
    | '/_main/search'
    | '/auth_/forgot-password'
    | '/auth_/login'
    | '/auth_/logout'
    | '/auth_/register'
    | '/auth_/reset-password'
    | '/auth_/verify'
    | '/dashboard_/account'
    | '/dashboard_/admin'
    | '/dashboard_/channels'
    | '/dashboard_/churches'
    | '/dashboard_/invitations'
    | '/dashboard_/organizations'
    | '/embed/churches'
    | '/invitations_/accept'
    | '/invitations_/expired'
    | '/invitations_/invalid'
    | '/media/rss.xml'
    | '/oidc/authorize'
    | '/oidc/logout'
    | '/oidc/token'
    | '/oidc/userinfo'
    | '/trpc/$'
    | '/_main/'
    | '/dashboard_/'
    | '/_main/about/add-church'
    | '/_main/about/add-content'
    | '/_main/about/dmca'
    | '/_main/about/dorean'
    | '/_main/about/privacy'
    | '/_main/about/terms'
    | '/_main/about/theology'
    | '/_main/channel/$slug'
    | '/_main/churches_/$slug'
    | '/_main/media/$mediaId'
    | '/_main/playlist/$playlistId'
    | '/_main/series/$seriesId'
    | '/channel/$slug/podcast.xml'
    | '/channel/$slug/rss.xml'
    | '/dashboard_/account_/newsletter'
    | '/dashboard_/account_/profile'
    | '/dashboard_/account_/security'
    | '/dashboard_/admin_/backfill-filenames'
    | '/dashboard_/admin_/channels'
    | '/dashboard_/admin_/deleting-uploads'
    | '/dashboard_/admin_/duplicate-uploads'
    | '/dashboard_/admin_/failed-annotations'
    | '/dashboard_/admin_/failed-summaries'
    | '/dashboard_/admin_/failed-uploads'
    | '/dashboard_/admin_/featured'
    | '/dashboard_/admin_/import-sources'
    | '/dashboard_/admin_/llm-eval'
    | '/dashboard_/admin_/maintenance'
    | '/dashboard_/admin_/newsletter-lists'
    | '/dashboard_/admin_/organization-tags'
    | '/dashboard_/admin_/organizations'
    | '/dashboard_/admin_/processing-uploads'
    | '/dashboard_/admin_/reindex'
    | '/dashboard_/admin_/reprocess'
    | '/dashboard_/admin_/searches'
    | '/dashboard_/admin_/storage-audit'
    | '/dashboard_/admin_/upload-backups'
    | '/dashboard_/admin_/users'
    | '/dashboard_/channels_/$channelId'
    | '/dashboard_/channels_/new'
    | '/dashboard_/churches_/$churchId'
    | '/dashboard_/churches_/new'
    | '/dashboard_/invitations_/accept'
    | '/dashboard_/organizations_/$orgId'
    | '/embed/channel/$slug'
    | '/embed/media/$mediaId'
    | '/playlist/$playlistId/rss.xml'
    | '/series/$seriesId/rss.xml'
    | '/_main/about/'
    | '/dashboard_/channels_/$channelId_/edit'
    | '/dashboard_/channels_/$channelId_/members'
    | '/dashboard_/channels_/$channelId_/playlists'
    | '/dashboard_/channels_/$channelId_/uploads'
    | '/dashboard_/churches_/$churchId_/channels'
    | '/dashboard_/churches_/$churchId_/edit'
    | '/dashboard_/churches_/$churchId_/leaders'
    | '/dashboard_/churches_/$churchId_/members'
    | '/dashboard_/organizations_/$orgId_/associations'
    | '/dashboard_/organizations_/$orgId_/edit'
    | '/dashboard_/organizations_/$orgId_/members'
    | '/dashboard_/channels_/$channelId_/playlists_/$playlistId'
    | '/dashboard_/channels_/$channelId_/uploads_/$uploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  EmbedChurchesRoute: typeof EmbedChurchesRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  InvitationsExpiredRoute: typeof InvitationsExpiredRoute
  InvitationsInvalidRoute: typeof InvitationsInvalidRoute
  MediaRssDotxmlRoute: typeof MediaRssDotxmlRoute
  OidcAuthorizeRoute: typeof OidcAuthorizeRoute
  OidcLogoutRoute: typeof OidcLogoutRoute
  OidcTokenRoute: typeof OidcTokenRoute
  OidcUserinfoRoute: typeof OidcUserinfoRoute
  TrpcSplatRoute: typeof TrpcSplatRoute
  ChannelSlugPodcastDotxmlRoute: typeof ChannelSlugPodcastDotxmlRoute
  ChannelSlugRssDotxmlRoute: typeof ChannelSlugRssDotxmlRoute
  EmbedChannelSlugRoute: typeof EmbedChannelSlugRoute
  EmbedMediaMediaIdRoute: typeof EmbedMediaMediaIdRoute
  PlaylistPlaylistIdRssDotxmlRoute: typeof PlaylistPlaylistIdRssDotxmlRoute
  SeriesSeriesIdRssDotxmlRoute: typeof SeriesSeriesIdRssDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_': {
      id: '/dashboard_'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_': {
      id: '/auth_'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/': {
      id: '/dashboard_/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/userinfo': {
      id: '/oidc/userinfo'
      path: '/oidc/userinfo'
      fullPath: '/oidc/userinfo'
      preLoaderRoute: typeof OidcUserinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/token': {
      id: '/oidc/token'
      path: '/oidc/token'
      fullPath: '/oidc/token'
      preLoaderRoute: typeof OidcTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/logout': {
      id: '/oidc/logout'
      path: '/oidc/logout'
      fullPath: '/oidc/logout'
      preLoaderRoute: typeof OidcLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/authorize': {
      id: '/oidc/authorize'
      path: '/oidc/authorize'
      fullPath: '/oidc/authorize'
      preLoaderRoute: typeof OidcAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/rss.xml': {
      id: '/media/rss.xml'
      path: '/media/rss.xml'
      fullPath: '/media/rss.xml'
      preLoaderRoute: typeof MediaRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations_/invalid': {
      id: '/invitations_/invalid'
      path: '/invitations/invalid'
      fullPath: '/invitations/invalid'
      preLoaderRoute: typeof InvitationsInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations_/expired': {
      id: '/invitations_/expired'
      path: '/invitations/expired'
      fullPath: '/invitations/expired'
      preLoaderRoute: typeof InvitationsExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations_/accept': {
      id: '/invitations_/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/churches': {
      id: '/embed/churches'
      path: '/embed/churches'
      fullPath: '/embed/churches'
      preLoaderRoute: typeof EmbedChurchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/organizations': {
      id: '/dashboard_/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/invitations': {
      id: '/dashboard_/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches': {
      id: '/dashboard_/churches'
      path: '/churches'
      fullPath: '/dashboard/churches'
      preLoaderRoute: typeof DashboardChurchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels': {
      id: '/dashboard_/channels'
      path: '/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin': {
      id: '/dashboard_/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account': {
      id: '/dashboard_/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth_/verify': {
      id: '/auth_/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/register': {
      id: '/auth_/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/logout': {
      id: '/auth_/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/login': {
      id: '/auth_/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/forgot-password': {
      id: '/auth_/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/library': {
      id: '/_main/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof MainLibraryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/history': {
      id: '/_main/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof MainHistoryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/following': {
      id: '/_main/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof MainFollowingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/churches': {
      id: '/_main/churches'
      path: '/churches'
      fullPath: '/churches'
      preLoaderRoute: typeof MainChurchesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/channels': {
      id: '/_main/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof MainChannelsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$slug': {
      id: '/_main/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof MainSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/admin_/reindex': {
      id: '/dashboard_/admin_/reindex'
      path: '/admin/reindex'
      fullPath: '/dashboard/admin/reindex'
      preLoaderRoute: typeof DashboardAdminReindexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_main/about/': {
      id: '/_main/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof MainAboutIndexRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/series/$seriesId/rss.xml': {
      id: '/series/$seriesId/rss.xml'
      path: '/series/$seriesId/rss.xml'
      fullPath: '/series/$seriesId/rss.xml'
      preLoaderRoute: typeof SeriesSeriesIdRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId/rss.xml': {
      id: '/playlist/$playlistId/rss.xml'
      path: '/playlist/$playlistId/rss.xml'
      fullPath: '/playlist/$playlistId/rss.xml'
      preLoaderRoute: typeof PlaylistPlaylistIdRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/media/$mediaId': {
      id: '/embed/media/$mediaId'
      path: '/embed/media/$mediaId'
      fullPath: '/embed/media/$mediaId'
      preLoaderRoute: typeof EmbedMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/channel/$slug': {
      id: '/embed/channel/$slug'
      path: '/embed/channel/$slug'
      fullPath: '/embed/channel/$slug'
      preLoaderRoute: typeof EmbedChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/organizations_/$orgId': {
      id: '/dashboard_/organizations_/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/dashboard/organizations/$orgId'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/invitations_/accept': {
      id: '/dashboard_/invitations_/accept'
      path: '/invitations/accept'
      fullPath: '/dashboard/invitations/accept'
      preLoaderRoute: typeof DashboardInvitationsAcceptRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/new': {
      id: '/dashboard_/churches_/new'
      path: '/churches/new'
      fullPath: '/dashboard/churches/new'
      preLoaderRoute: typeof DashboardChurchesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId': {
      id: '/dashboard_/churches_/$churchId'
      path: '/churches/$churchId'
      fullPath: '/dashboard/churches/$churchId'
      preLoaderRoute: typeof DashboardChurchesChurchIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/new': {
      id: '/dashboard_/channels_/new'
      path: '/channels/new'
      fullPath: '/dashboard/channels/new'
      preLoaderRoute: typeof DashboardChannelsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId': {
      id: '/dashboard_/channels_/$channelId'
      path: '/channels/$channelId'
      fullPath: '/dashboard/channels/$channelId'
      preLoaderRoute: typeof DashboardChannelsChannelIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/users': {
      id: '/dashboard_/admin_/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/upload-backups': {
      id: '/dashboard_/admin_/upload-backups'
      path: '/admin/upload-backups'
      fullPath: '/dashboard/admin/upload-backups'
      preLoaderRoute: typeof DashboardAdminUploadBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/storage-audit': {
      id: '/dashboard_/admin_/storage-audit'
      path: '/admin/storage-audit'
      fullPath: '/dashboard/admin/storage-audit'
      preLoaderRoute: typeof DashboardAdminStorageAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/searches': {
      id: '/dashboard_/admin_/searches'
      path: '/admin/searches'
      fullPath: '/dashboard/admin/searches'
      preLoaderRoute: typeof DashboardAdminSearchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/reprocess': {
      id: '/dashboard_/admin_/reprocess'
      path: '/admin/reprocess'
      fullPath: '/dashboard/admin/reprocess'
      preLoaderRoute: typeof DashboardAdminReprocessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/processing-uploads': {
      id: '/dashboard_/admin_/processing-uploads'
      path: '/admin/processing-uploads'
      fullPath: '/dashboard/admin/processing-uploads'
      preLoaderRoute: typeof DashboardAdminProcessingUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/organizations': {
      id: '/dashboard_/admin_/organizations'
      path: '/admin/organizations'
      fullPath: '/dashboard/admin/organizations'
      preLoaderRoute: typeof DashboardAdminOrganizationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/organization-tags': {
      id: '/dashboard_/admin_/organization-tags'
      path: '/admin/organization-tags'
      fullPath: '/dashboard/admin/organization-tags'
      preLoaderRoute: typeof DashboardAdminOrganizationTagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/newsletter-lists': {
      id: '/dashboard_/admin_/newsletter-lists'
      path: '/admin/newsletter-lists'
      fullPath: '/dashboard/admin/newsletter-lists'
      preLoaderRoute: typeof DashboardAdminNewsletterListsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/maintenance': {
      id: '/dashboard_/admin_/maintenance'
      path: '/admin/maintenance'
      fullPath: '/dashboard/admin/maintenance'
      preLoaderRoute: typeof DashboardAdminMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/llm-eval': {
      id: '/dashboard_/admin_/llm-eval'
      path: '/admin/llm-eval'
      fullPath: '/dashboard/admin/llm-eval'
      preLoaderRoute: typeof DashboardAdminLlmEvalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/import-sources': {
      id: '/dashboard_/admin_/import-sources'
      path: '/admin/import-sources'
      fullPath: '/dashboard/admin/import-sources'
      preLoaderRoute: typeof DashboardAdminImportSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/featured': {
      id: '/dashboard_/admin_/featured'
      path: '/admin/featured'
      fullPath: '/dashboard/admin/featured'
      preLoaderRoute: typeof DashboardAdminFeaturedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/failed-uploads': {
      id: '/dashboard_/admin_/failed-uploads'
      path: '/admin/failed-uploads'
      fullPath: '/dashboard/admin/failed-uploads'
      preLoaderRoute: typeof DashboardAdminFailedUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/failed-summaries': {
      id: '/dashboard_/admin_/failed-summaries'
      path: '/admin/failed-summaries'
      fullPath: '/dashboard/admin/failed-summaries'
      preLoaderRoute: typeof DashboardAdminFailedSummariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/failed-annotations': {
      id: '/dashboard_/admin_/failed-annotations'
      path: '/admin/failed-annotations'
      fullPath: '/dashboard/admin/failed-annotations'
      preLoaderRoute: typeof DashboardAdminFailedAnnotationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/duplicate-uploads': {
      id: '/dashboard_/admin_/duplicate-uploads'
      path: '/admin/duplicate-uploads'
      fullPath: '/dashboard/admin/duplicate-uploads'
      preLoaderRoute: typeof DashboardAdminDuplicateUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/deleting-uploads': {
      id: '/dashboard_/admin_/deleting-uploads'
      path: '/admin/deleting-uploads'
      fullPath: '/dashboard/admin/deleting-uploads'
      preLoaderRoute: typeof DashboardAdminDeletingUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/channels': {
      id: '/dashboard_/admin_/channels'
      path: '/admin/channels'
      fullPath: '/dashboard/admin/channels'
      preLoaderRoute: typeof DashboardAdminChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/backfill-filenames': {
      id: '/dashboard_/admin_/backfill-filenames'
      path: '/admin/backfill-filenames'
      fullPath: '/dashboard/admin/backfill-filenames'
      preLoaderRoute: typeof DashboardAdminBackfillFilenamesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account_/security': {
      id: '/dashboard_/account_/security'
      path: '/account/security'
      fullPath: '/dashboard/account/security'
      preLoaderRoute: typeof DashboardAccountSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account_/profile': {
      id: '/dashboard_/account_/profile'
      path: '/account/profile'
      fullPath: '/dashboard/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account_/newsletter': {
      id: '/dashboard_/account_/newsletter'
      path: '/account/newsletter'
      fullPath: '/dashboard/account/newsletter'
      preLoaderRoute: typeof DashboardAccountNewsletterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/channel/$slug/rss.xml': {
      id: '/channel/$slug/rss.xml'
      path: '/channel/$slug/rss.xml'
      fullPath: '/channel/$slug/rss.xml'
      preLoaderRoute: typeof ChannelSlugRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$slug/podcast.xml': {
      id: '/channel/$slug/podcast.xml'
      path: '/channel/$slug/podcast.xml'
      fullPath: '/channel/$slug/podcast.xml'
      preLoaderRoute: typeof ChannelSlugPodcastDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/series/$seriesId': {
      id: '/_main/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof MainSeriesSeriesIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/playlist/$playlistId': {
      id: '/_main/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof MainPlaylistPlaylistIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/media/$mediaId': {
      id: '/_main/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MainMediaMediaIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/churches_/$slug': {
      id: '/_main/churches_/$slug'
      path: '/churches/$slug'
      fullPath: '/churches/$slug'
      preLoaderRoute: typeof MainChurchesSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/channel/$slug': {
      id: '/_main/channel/$slug'
      path: '/channel/$slug'
      fullPath: '/channel/$slug'
      preLoaderRoute: typeof MainChannelSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about/theology': {
      id: '/_main/about/theology'
      path: '/theology'
      fullPath: '/about/theology'
      preLoaderRoute: typeof MainAboutTheologyRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/_main/about/terms': {
      id: '/_main/about/terms'
      path: '/terms'
      fullPath: '/about/terms'
      preLoaderRoute: typeof MainAboutTermsRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/_main/about/privacy': {
      id: '/_main/about/privacy'
      path: '/privacy'
      fullPath: '/about/privacy'
      preLoaderRoute: typeof MainAboutPrivacyRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/_main/about/dorean': {
      id: '/_main/about/dorean'
      path: '/dorean'
      fullPath: '/about/dorean'
      preLoaderRoute: typeof MainAboutDoreanRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/_main/about/dmca': {
      id: '/_main/about/dmca'
      path: '/dmca'
      fullPath: '/about/dmca'
      preLoaderRoute: typeof MainAboutDmcaRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/_main/about/add-content': {
      id: '/_main/about/add-content'
      path: '/add-content'
      fullPath: '/about/add-content'
      preLoaderRoute: typeof MainAboutAddContentRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/_main/about/add-church': {
      id: '/_main/about/add-church'
      path: '/add-church'
      fullPath: '/about/add-church'
      preLoaderRoute: typeof MainAboutAddChurchRouteImport
      parentRoute: typeof MainAboutRoute
    }
    '/dashboard_/organizations_/$orgId_/members': {
      id: '/dashboard_/organizations_/$orgId_/members'
      path: '/organizations/$orgId/members'
      fullPath: '/dashboard/organizations/$orgId/members'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/organizations_/$orgId_/edit': {
      id: '/dashboard_/organizations_/$orgId_/edit'
      path: '/organizations/$orgId/edit'
      fullPath: '/dashboard/organizations/$orgId/edit'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/organizations_/$orgId_/associations': {
      id: '/dashboard_/organizations_/$orgId_/associations'
      path: '/organizations/$orgId/associations'
      fullPath: '/dashboard/organizations/$orgId/associations'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdAssociationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/members': {
      id: '/dashboard_/churches_/$churchId_/members'
      path: '/churches/$churchId/members'
      fullPath: '/dashboard/churches/$churchId/members'
      preLoaderRoute: typeof DashboardChurchesChurchIdMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/leaders': {
      id: '/dashboard_/churches_/$churchId_/leaders'
      path: '/churches/$churchId/leaders'
      fullPath: '/dashboard/churches/$churchId/leaders'
      preLoaderRoute: typeof DashboardChurchesChurchIdLeadersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/edit': {
      id: '/dashboard_/churches_/$churchId_/edit'
      path: '/churches/$churchId/edit'
      fullPath: '/dashboard/churches/$churchId/edit'
      preLoaderRoute: typeof DashboardChurchesChurchIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/channels': {
      id: '/dashboard_/churches_/$churchId_/channels'
      path: '/churches/$churchId/channels'
      fullPath: '/dashboard/churches/$churchId/channels'
      preLoaderRoute: typeof DashboardChurchesChurchIdChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/uploads': {
      id: '/dashboard_/channels_/$channelId_/uploads'
      path: '/channels/$channelId/uploads'
      fullPath: '/dashboard/channels/$channelId/uploads'
      preLoaderRoute: typeof DashboardChannelsChannelIdUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/playlists': {
      id: '/dashboard_/channels_/$channelId_/playlists'
      path: '/channels/$channelId/playlists'
      fullPath: '/dashboard/channels/$channelId/playlists'
      preLoaderRoute: typeof DashboardChannelsChannelIdPlaylistsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/members': {
      id: '/dashboard_/channels_/$channelId_/members'
      path: '/channels/$channelId/members'
      fullPath: '/dashboard/channels/$channelId/members'
      preLoaderRoute: typeof DashboardChannelsChannelIdMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/edit': {
      id: '/dashboard_/channels_/$channelId_/edit'
      path: '/channels/$channelId/edit'
      fullPath: '/dashboard/channels/$channelId/edit'
      preLoaderRoute: typeof DashboardChannelsChannelIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/uploads_/$uploadId': {
      id: '/dashboard_/channels_/$channelId_/uploads_/$uploadId'
      path: '/channels/$channelId/uploads/$uploadId'
      fullPath: '/dashboard/channels/$channelId/uploads/$uploadId'
      preLoaderRoute: typeof DashboardChannelsChannelIdUploadsUploadIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/playlists_/$playlistId': {
      id: '/dashboard_/channels_/$channelId_/playlists_/$playlistId'
      path: '/channels/$channelId/playlists/$playlistId'
      fullPath: '/dashboard/channels/$channelId/playlists/$playlistId'
      preLoaderRoute: typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface MainAboutRouteChildren {
  MainAboutAddChurchRoute: typeof MainAboutAddChurchRoute
  MainAboutAddContentRoute: typeof MainAboutAddContentRoute
  MainAboutDmcaRoute: typeof MainAboutDmcaRoute
  MainAboutDoreanRoute: typeof MainAboutDoreanRoute
  MainAboutPrivacyRoute: typeof MainAboutPrivacyRoute
  MainAboutTermsRoute: typeof MainAboutTermsRoute
  MainAboutTheologyRoute: typeof MainAboutTheologyRoute
  MainAboutIndexRoute: typeof MainAboutIndexRoute
}

const MainAboutRouteChildren: MainAboutRouteChildren = {
  MainAboutAddChurchRoute: MainAboutAddChurchRoute,
  MainAboutAddContentRoute: MainAboutAddContentRoute,
  MainAboutDmcaRoute: MainAboutDmcaRoute,
  MainAboutDoreanRoute: MainAboutDoreanRoute,
  MainAboutPrivacyRoute: MainAboutPrivacyRoute,
  MainAboutTermsRoute: MainAboutTermsRoute,
  MainAboutTheologyRoute: MainAboutTheologyRoute,
  MainAboutIndexRoute: MainAboutIndexRoute,
}

const MainAboutRouteWithChildren = MainAboutRoute._addFileChildren(
  MainAboutRouteChildren,
)

interface MainRouteChildren {
  MainSlugRoute: typeof MainSlugRoute
  MainAboutRoute: typeof MainAboutRouteWithChildren
  MainChannelsRoute: typeof MainChannelsRoute
  MainChurchesRoute: typeof MainChurchesRoute
  MainFollowingRoute: typeof MainFollowingRoute
  MainHistoryRoute: typeof MainHistoryRoute
  MainLibraryRoute: typeof MainLibraryRoute
  MainSearchRoute: typeof MainSearchRoute
  MainIndexRoute: typeof MainIndexRoute
  MainChannelSlugRoute: typeof MainChannelSlugRoute
  MainChurchesSlugRoute: typeof MainChurchesSlugRoute
  MainMediaMediaIdRoute: typeof MainMediaMediaIdRoute
  MainPlaylistPlaylistIdRoute: typeof MainPlaylistPlaylistIdRoute
  MainSeriesSeriesIdRoute: typeof MainSeriesSeriesIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSlugRoute: MainSlugRoute,
  MainAboutRoute: MainAboutRouteWithChildren,
  MainChannelsRoute: MainChannelsRoute,
  MainChurchesRoute: MainChurchesRoute,
  MainFollowingRoute: MainFollowingRoute,
  MainHistoryRoute: MainHistoryRoute,
  MainLibraryRoute: MainLibraryRoute,
  MainSearchRoute: MainSearchRoute,
  MainIndexRoute: MainIndexRoute,
  MainChannelSlugRoute: MainChannelSlugRoute,
  MainChurchesSlugRoute: MainChurchesSlugRoute,
  MainMediaMediaIdRoute: MainMediaMediaIdRoute,
  MainPlaylistPlaylistIdRoute: MainPlaylistPlaylistIdRoute,
  MainSeriesSeriesIdRoute: MainSeriesSeriesIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardChannelsRoute: typeof DashboardChannelsRoute
  DashboardChurchesRoute: typeof DashboardChurchesRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardOrganizationsRoute: typeof DashboardOrganizationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountNewsletterRoute: typeof DashboardAccountNewsletterRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountSecurityRoute: typeof DashboardAccountSecurityRoute
  DashboardAdminBackfillFilenamesRoute: typeof DashboardAdminBackfillFilenamesRoute
  DashboardAdminChannelsRoute: typeof DashboardAdminChannelsRoute
  DashboardAdminDeletingUploadsRoute: typeof DashboardAdminDeletingUploadsRoute
  DashboardAdminDuplicateUploadsRoute: typeof DashboardAdminDuplicateUploadsRoute
  DashboardAdminFailedAnnotationsRoute: typeof DashboardAdminFailedAnnotationsRoute
  DashboardAdminFailedSummariesRoute: typeof DashboardAdminFailedSummariesRoute
  DashboardAdminFailedUploadsRoute: typeof DashboardAdminFailedUploadsRoute
  DashboardAdminFeaturedRoute: typeof DashboardAdminFeaturedRoute
  DashboardAdminImportSourcesRoute: typeof DashboardAdminImportSourcesRoute
  DashboardAdminLlmEvalRoute: typeof DashboardAdminLlmEvalRoute
  DashboardAdminMaintenanceRoute: typeof DashboardAdminMaintenanceRoute
  DashboardAdminNewsletterListsRoute: typeof DashboardAdminNewsletterListsRoute
  DashboardAdminOrganizationTagsRoute: typeof DashboardAdminOrganizationTagsRoute
  DashboardAdminOrganizationsRoute: typeof DashboardAdminOrganizationsRoute
  DashboardAdminProcessingUploadsRoute: typeof DashboardAdminProcessingUploadsRoute
  DashboardAdminReindexRoute: typeof DashboardAdminReindexRoute
  DashboardAdminReprocessRoute: typeof DashboardAdminReprocessRoute
  DashboardAdminSearchesRoute: typeof DashboardAdminSearchesRoute
  DashboardAdminStorageAuditRoute: typeof DashboardAdminStorageAuditRoute
  DashboardAdminUploadBackupsRoute: typeof DashboardAdminUploadBackupsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardChannelsChannelIdRoute: typeof DashboardChannelsChannelIdRoute
  DashboardChannelsNewRoute: typeof DashboardChannelsNewRoute
  DashboardChurchesChurchIdRoute: typeof DashboardChurchesChurchIdRoute
  DashboardChurchesNewRoute: typeof DashboardChurchesNewRoute
  DashboardInvitationsAcceptRoute: typeof DashboardInvitationsAcceptRoute
  DashboardOrganizationsOrgIdRoute: typeof DashboardOrganizationsOrgIdRoute
  DashboardChannelsChannelIdEditRoute: typeof DashboardChannelsChannelIdEditRoute
  DashboardChannelsChannelIdMembersRoute: typeof DashboardChannelsChannelIdMembersRoute
  DashboardChannelsChannelIdPlaylistsRoute: typeof DashboardChannelsChannelIdPlaylistsRoute
  DashboardChannelsChannelIdUploadsRoute: typeof DashboardChannelsChannelIdUploadsRoute
  DashboardChurchesChurchIdChannelsRoute: typeof DashboardChurchesChurchIdChannelsRoute
  DashboardChurchesChurchIdEditRoute: typeof DashboardChurchesChurchIdEditRoute
  DashboardChurchesChurchIdLeadersRoute: typeof DashboardChurchesChurchIdLeadersRoute
  DashboardChurchesChurchIdMembersRoute: typeof DashboardChurchesChurchIdMembersRoute
  DashboardOrganizationsOrgIdAssociationsRoute: typeof DashboardOrganizationsOrgIdAssociationsRoute
  DashboardOrganizationsOrgIdEditRoute: typeof DashboardOrganizationsOrgIdEditRoute
  DashboardOrganizationsOrgIdMembersRoute: typeof DashboardOrganizationsOrgIdMembersRoute
  DashboardChannelsChannelIdPlaylistsPlaylistIdRoute: typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  DashboardChannelsChannelIdUploadsUploadIdRoute: typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardChannelsRoute: DashboardChannelsRoute,
  DashboardChurchesRoute: DashboardChurchesRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardOrganizationsRoute: DashboardOrganizationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountNewsletterRoute: DashboardAccountNewsletterRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountSecurityRoute: DashboardAccountSecurityRoute,
  DashboardAdminBackfillFilenamesRoute: DashboardAdminBackfillFilenamesRoute,
  DashboardAdminChannelsRoute: DashboardAdminChannelsRoute,
  DashboardAdminDeletingUploadsRoute: DashboardAdminDeletingUploadsRoute,
  DashboardAdminDuplicateUploadsRoute: DashboardAdminDuplicateUploadsRoute,
  DashboardAdminFailedAnnotationsRoute: DashboardAdminFailedAnnotationsRoute,
  DashboardAdminFailedSummariesRoute: DashboardAdminFailedSummariesRoute,
  DashboardAdminFailedUploadsRoute: DashboardAdminFailedUploadsRoute,
  DashboardAdminFeaturedRoute: DashboardAdminFeaturedRoute,
  DashboardAdminImportSourcesRoute: DashboardAdminImportSourcesRoute,
  DashboardAdminLlmEvalRoute: DashboardAdminLlmEvalRoute,
  DashboardAdminMaintenanceRoute: DashboardAdminMaintenanceRoute,
  DashboardAdminNewsletterListsRoute: DashboardAdminNewsletterListsRoute,
  DashboardAdminOrganizationTagsRoute: DashboardAdminOrganizationTagsRoute,
  DashboardAdminOrganizationsRoute: DashboardAdminOrganizationsRoute,
  DashboardAdminProcessingUploadsRoute: DashboardAdminProcessingUploadsRoute,
  DashboardAdminReindexRoute: DashboardAdminReindexRoute,
  DashboardAdminReprocessRoute: DashboardAdminReprocessRoute,
  DashboardAdminSearchesRoute: DashboardAdminSearchesRoute,
  DashboardAdminStorageAuditRoute: DashboardAdminStorageAuditRoute,
  DashboardAdminUploadBackupsRoute: DashboardAdminUploadBackupsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardChannelsChannelIdRoute: DashboardChannelsChannelIdRoute,
  DashboardChannelsNewRoute: DashboardChannelsNewRoute,
  DashboardChurchesChurchIdRoute: DashboardChurchesChurchIdRoute,
  DashboardChurchesNewRoute: DashboardChurchesNewRoute,
  DashboardInvitationsAcceptRoute: DashboardInvitationsAcceptRoute,
  DashboardOrganizationsOrgIdRoute: DashboardOrganizationsOrgIdRoute,
  DashboardChannelsChannelIdEditRoute: DashboardChannelsChannelIdEditRoute,
  DashboardChannelsChannelIdMembersRoute:
    DashboardChannelsChannelIdMembersRoute,
  DashboardChannelsChannelIdPlaylistsRoute:
    DashboardChannelsChannelIdPlaylistsRoute,
  DashboardChannelsChannelIdUploadsRoute:
    DashboardChannelsChannelIdUploadsRoute,
  DashboardChurchesChurchIdChannelsRoute:
    DashboardChurchesChurchIdChannelsRoute,
  DashboardChurchesChurchIdEditRoute: DashboardChurchesChurchIdEditRoute,
  DashboardChurchesChurchIdLeadersRoute: DashboardChurchesChurchIdLeadersRoute,
  DashboardChurchesChurchIdMembersRoute: DashboardChurchesChurchIdMembersRoute,
  DashboardOrganizationsOrgIdAssociationsRoute:
    DashboardOrganizationsOrgIdAssociationsRoute,
  DashboardOrganizationsOrgIdEditRoute: DashboardOrganizationsOrgIdEditRoute,
  DashboardOrganizationsOrgIdMembersRoute:
    DashboardOrganizationsOrgIdMembersRoute,
  DashboardChannelsChannelIdPlaylistsPlaylistIdRoute:
    DashboardChannelsChannelIdPlaylistsPlaylistIdRoute,
  DashboardChannelsChannelIdUploadsUploadIdRoute:
    DashboardChannelsChannelIdUploadsUploadIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  EmbedChurchesRoute: EmbedChurchesRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  InvitationsExpiredRoute: InvitationsExpiredRoute,
  InvitationsInvalidRoute: InvitationsInvalidRoute,
  MediaRssDotxmlRoute: MediaRssDotxmlRoute,
  OidcAuthorizeRoute: OidcAuthorizeRoute,
  OidcLogoutRoute: OidcLogoutRoute,
  OidcTokenRoute: OidcTokenRoute,
  OidcUserinfoRoute: OidcUserinfoRoute,
  TrpcSplatRoute: TrpcSplatRoute,
  ChannelSlugPodcastDotxmlRoute: ChannelSlugPodcastDotxmlRoute,
  ChannelSlugRssDotxmlRoute: ChannelSlugRssDotxmlRoute,
  EmbedChannelSlugRoute: EmbedChannelSlugRoute,
  EmbedMediaMediaIdRoute: EmbedMediaMediaIdRoute,
  PlaylistPlaylistIdRssDotxmlRoute: PlaylistPlaylistIdRssDotxmlRoute,
  SeriesSeriesIdRssDotxmlRoute: SeriesSeriesIdRssDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
