export default {
  type: 'FeatureCollection',
  query: ['roanoke', 'virginia', 'united', 'states'],
  features: [
    {
      id: 'place.279898348',
      type: 'Feature',
      place_type: ['place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpFSzdvN0E',
        wikidata: 'Q501796',
      },
      text: 'Roanoke',
      place_name: 'Roanoke, Virginia, United States',
      matching_place_name: 'Roanoke, Virginia, United States of America',
      bbox: [-80.143349, 37.160634, -79.817801, 37.402362],
      center: [-79.941431, 37.270973],
      geometry: { type: 'Point', coordinates: [-79.941431, 37.270973] },
      context: [
        {
          id: 'district.19973868',
          mapbox_id: 'dXJuOm1ieHBsYzpBVERHN0E',
          wikidata: 'Q501796',
          text: 'Roanoke city',
        },
        {
          id: 'region.91372',
          mapbox_id: 'dXJuOm1ieHBsYzpBV1Rz',
          wikidata: 'Q1370',
          short_code: 'US-VA',
          text: 'Virginia',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text: 'United States',
        },
      ],
    },
    {
      id: 'district.19973868',
      type: 'Feature',
      place_type: ['district'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBVERHN0E',
        wikidata: 'Q501796',
      },
      text: 'Roanoke city',
      place_name: 'Roanoke city, Virginia, United States',
      matching_text: 'Roanoke',
      matching_place_name: 'Roanoke, Virginia, United States of America',
      bbox: [-80.037581, 37.211899, -79.87855, 37.337629],
      center: [-79.941431, 37.270973],
      geometry: { type: 'Point', coordinates: [-79.941431, 37.270973] },
      context: [
        {
          id: 'region.91372',
          mapbox_id: 'dXJuOm1ieHBsYzpBV1Rz',
          wikidata: 'Q1370',
          short_code: 'US-VA',
          text: 'Virginia',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text: 'United States',
        },
      ],
    },
    {
      id: 'poi.197568563213',
      type: 'Feature',
      place_type: ['poi'],
      relevance: 1,
      properties: {
        foursquare: '4bd71fb8304fce72191c33ab',
        landmark: true,
        address: '7860 Plantation Rd',
        category: 'hotel, motel, tourism, lodging',
      },
      text: 'Country Inn & Suites by Radisson',
      place_name:
        'Country Inn & Suites by Radisson, 7860 Plantation Rd, Hollins, Virginia 24019, United States',
      matching_text: 'Roanoke',
      matching_place_name:
        'Roanoke, 7860 Plantation Rd, Hollins, Virginia 24019, United States of America',
      center: [-79.956812, 37.354612],
      geometry: { coordinates: [-79.956812, 37.354612], type: 'Point' },
      context: [
        {
          id: 'neighborhood.654642412',
          mapbox_id: 'dXJuOm1ieHBsYzpKd1VNN0E',
          text: 'Tinker Knoll',
        },
        {
          id: 'postcode.74985196',
          mapbox_id: 'dXJuOm1ieHBsYzpCSGd1N0E',
          text: '24019',
        },
        {
          id: 'place.151652588',
          mapbox_id: 'dXJuOm1ieHBsYzpDUW9JN0E',
          text: 'Hollins',
        },
        {
          id: 'district.19982060',
          mapbox_id: 'dXJuOm1ieHBsYzpBVERtN0E',
          wikidata: 'Q513968',
          text: 'Roanoke County',
        },
        {
          id: 'region.91372',
          mapbox_id: 'dXJuOm1ieHBsYzpBV1Rz',
          wikidata: 'Q1370',
          short_code: 'US-VA',
          text: 'Virginia',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text: 'United States',
        },
      ],
    },
    {
      id: 'poi.1202590882481',
      type: 'Feature',
      place_type: ['poi'],
      relevance: 1,
      properties: {
        foursquare: '4db477be43a1369cb5bb6928',
        landmark: true,
        address: 'wasina park /bennington ave',
        category: 'hiking, trailhead, hike, hiking trailhead',
      },
      text: 'Roanoke River Greenway',
      place_name:
        'Roanoke River Greenway, wasina park /bennington ave, Roanoke, Virginia 24015, United States',
      matching_text: 'Roanoke',
      matching_place_name:
        'Roanoke, wasina park /bennington ave, Roanoke, Virginia 24015, United States of America',
      center: [-79.978971, 37.266176],
      geometry: { coordinates: [-79.978971, 37.266176], type: 'Point' },
      context: [
        {
          id: 'neighborhood.524446956',
          mapbox_id: 'dXJuOm1ieHBsYzpIMEpzN0E',
          wikidata: 'Q7286906',
          text: 'Raleigh Court',
        },
        {
          id: 'postcode.74952428',
          mapbox_id: 'dXJuOm1ieHBsYzpCSGV1N0E',
          text: '24015',
        },
        {
          id: 'place.279898348',
          mapbox_id: 'dXJuOm1ieHBsYzpFSzdvN0E',
          wikidata: 'Q501796',
          text: 'Roanoke',
        },
        {
          id: 'district.19973868',
          mapbox_id: 'dXJuOm1ieHBsYzpBVERHN0E',
          wikidata: 'Q501796',
          text: 'Roanoke city',
        },
        {
          id: 'region.91372',
          mapbox_id: 'dXJuOm1ieHBsYzpBV1Rz',
          wikidata: 'Q1370',
          short_code: 'US-VA',
          text: 'Virginia',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text: 'United States',
        },
      ],
    },
    {
      id: 'poi.755914279030',
      type: 'Feature',
      place_type: ['poi'],
      relevance: 0.851852,
      properties: {
        foursquare: '4b900a96f964a520f17133e3',
        landmark: true,
        address: '4069 Postal Dr',
        category: 'post office, mail',
        maki: 'post',
      },
      text: 'United States Postal Service',
      place_name:
        'United States Postal Service, 4069 Postal Dr, Roanoke, Virginia 24018, United States',
      center: [-80.01132, 37.233081999999996],
      geometry: {
        coordinates: [-80.01132, 37.233081999999996],
        type: 'Point',
      },
      context: [
        {
          id: 'neighborhood.146918636',
          mapbox_id: 'dXJuOm1ieHBsYzpDTUhNN0E',
          text: 'Crestwood',
        },
        {
          id: 'postcode.74977004',
          mapbox_id: 'dXJuOm1ieHBsYzpCSGdPN0E',
          text: '24018',
        },
        {
          id: 'locality.91482860',
          mapbox_id: 'dXJuOm1ieHBsYzpCWFBxN0E',
          wikidata: 'Q1374740',
          text: 'Cave Spring',
        },
        {
          id: 'place.279898348',
          mapbox_id: 'dXJuOm1ieHBsYzpFSzdvN0E',
          wikidata: 'Q501796',
          text: 'Roanoke',
        },
        {
          id: 'district.19982060',
          mapbox_id: 'dXJuOm1ieHBsYzpBVERtN0E',
          wikidata: 'Q513968',
          text: 'Roanoke County',
        },
        {
          id: 'region.91372',
          mapbox_id: 'dXJuOm1ieHBsYzpBV1Rz',
          wikidata: 'Q1370',
          short_code: 'US-VA',
          text: 'Virginia',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text: 'United States',
        },
      ],
    },
  ],
  attribution:
    'NOTICE: © 2024 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare.',
} as const;
