---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: gateway-config
data:
  POSTGRES_HOST: "postgres:5432"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  MEDIA_URL: "$MEDIA_URL"
  ZXCVBN_MINIMUM_SCORE: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: temporal-server-config
data:
  SKIP_DB_CREATE: "true"
  DB: postgresql # Database vendor
  DB_PORT: "5432" # Database port
  POSTGRES_SEEDS: postgres # Database server
  DBNAME: temporal
  VISIBILITY_DBNAME: temporal
  DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/production-sql.yml
  ENABLE_ES: "true"
  ES_SEEDS: elasticsearch
  ES_VERSION: v7 # Even though we run v8, temporal only has configuration for v7
---
apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: temporal-server-secrets
data:
  POSTGRES_USER: $TEMPORAL_POSTGRES_USER_BASE64
  POSTGRES_PWD: $TEMPORAL_POSTGRES_PASSWORD_BASE64
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: temporal-server-dynamic-config
data:
  empty: |
  yaml: |
    limit.maxIDLength:
      - value: 255
        constraints: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: temporal-client-config
data:
  TEMPORAL_ADDRESS: temporal:7233
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: background-worker-config
data:
  TEMPORAL_SHUTDOWN_GRACE_TIME: 1m
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: process-upload-worker-config
data:
  TEMPORAL_SHUTDOWN_GRACE_TIME: 1h
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: elasticsearch-config
data:
  cluster.routing.allocation.disk.threshold_enabled: "true"
  cluster.routing.allocation.disk.watermark.low: 512mb
  cluster.routing.allocation.disk.watermark.high: 256mb
  cluster.routing.allocation.disk.watermark.flood_stage: 128mb
  discovery.type: single-node
  ES_JAVA_OPTS: -Xms256m -Xmx256m
  xpack.security.enabled: "false"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: postgres-credentials
data:
  # TODO: split this into two secrets, postgres-init and gateway-db-something
  DATABASE_URL: "$DATABASE_URL_BASE64"
  POSTGRES_PASSWORD: "$POSTGRES_PASSWORD_BASE64"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: postgres-config
data:
  POSTGRES_DB: letschurch
---
apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: postgres-initsql
data:
  SQL: $INIT_SQL_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: jwt-secret
data:
  JWT_SECRET: $JWT_SECRET_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: s3-secret
data:
  S3_INGEST_REGION: $S3_INGEST_REGION_BASE64
  S3_INGEST_ENDPOINT: $S3_INGEST_ENDPOINT_BASE64
  S3_INGEST_BUCKET: $S3_INGEST_BUCKET_BASE64
  S3_INGEST_ACCESS_KEY_ID: $S3_INGEST_ACCESS_KEY_ID_BASE64
  S3_INGEST_SECRET_ACCESS_KEY: $S3_INGEST_SECRET_ACCESS_KEY_BASE64
  S3_PUBLIC_REGION: $S3_PUBLIC_REGION_BASE64
  S3_PUBLIC_ENDPOINT: $S3_PUBLIC_ENDPOINT_BASE64
  S3_PUBLIC_BUCKET: $S3_PUBLIC_BUCKET_BASE64
  S3_PUBLIC_ACCESS_KEY_ID: $S3_PUBLIC_ACCESS_KEY_ID_BASE64
  S3_PUBLIC_SECRET_ACCESS_KEY: $S3_PUBLIC_SECRET_ACCESS_KEY_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: smtp-secret
data:
  SMTP_URL: $SMTP_URL_BASE64
