#!/usr/bin/env bash

set -v

required_vars=(
  CI_COMMIT_SHORT_SHA
  NAMESPACE
  MEDIA_URL
  API_HOST
  INIT_SQL_BASE64
  TEMPORAL_POSTGRES_USER_BASE64
  TEMPORAL_POSTGRES_PASSWORD_BASE64
  DATABASE_URL_BASE64
  POSTGRES_USER_BASE64
  POSTGRES_PASSWORD_BASE64
  JWT_SECRET_BASE64
  S3_INGEST_REGION_BASE64
  S3_INGEST_ENDPOINT_BASE64
  S3_INGEST_BUCKET_BASE64
  S3_INGEST_ACCESS_KEY_ID_BASE64
  S3_INGEST_SECRET_ACCESS_KEY_BASE64
  S3_PUBLIC_REGION_BASE64
  S3_PUBLIC_ENDPOINT_BASE64
  S3_PUBLIC_BUCKET_BASE64
  S3_PUBLIC_ACCESS_KEY_ID_BASE64
  S3_PUBLIC_SECRET_ACCESS_KEY_BASE64
  SMTP_URL_BASE64
)

for var in "${required_vars[@]}"; do
  if [ -z "${!var}" ]; then
    echo "Error: $var is not set."
    exit 1
  fi
done

cat *.yml | envsubst | kubectl apply -f -
