---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-worker
  labels:
    app: background-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background-worker
  template:
    metadata:
      labels:
        app: background-worker
    spec:
      restartPolicy: Always
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/background-worker:latest
          name: background-worker
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-letschurch
                  key: uri
            - name: OTEL_SERVICE_NAME
              value: background-worker
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_BACKGROUND_WORKER_DSN
          envFrom:
            - configMapRef:
                name: gateway-config
            - configMapRef:
                name: temporal-client-config
            - configMapRef:
                name: background-worker-config
            - secretRef:
                name: otel-secret
            - secretRef:
                name: s3-secret
            - secretRef:
                name: smtp-secret
