---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-worker
  labels:
    app: background-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background-worker
  template:
    metadata:
      labels:
        app: background-worker
    spec:
      restartPolicy: Always
      initContainers:
        - name: db-migrate
          image: registry.gitlab.com/letschurch/lets.church/background-worker:latest
          command: ["sh", "-c", "cd /usr/src/app/packages/db && pnpm run db:migrate"]
          envFrom:
            - configMapRef:
                name: web-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-letschurch
                  key: uri
        - name: elasticsearch-migrate
          image: registry.gitlab.com/letschurch/lets.church/background-worker:latest
          command: ["sh", "-c", "cd /usr/src/app/packages/elasticsearch && pnpm run push-mappings"]
          envFrom:
            - configMapRef:
                name: web-config
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/background-worker:latest
          name: background-worker
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-letschurch
                  key: uri
            - name: MAPBOX_GEOCODING_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mapbox-secret
                  key: MAPBOX_GEOCODING_TOKEN
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_BACKGROUND_WORKER_DSN
            - name: SERVICE_NAME
              value: background-worker
          envFrom:
            - configMapRef:
                name: web-config
            - configMapRef:
                name: temporal-client-config
            - configMapRef:
                name: background-worker-config
            - secretRef:
                name: axiom-pino-secret
            - secretRef:
                name: s3-ingest-secret
            - secretRef:
                name: s3-public-secret
            - secretRef:
                name: s3-backup-secret
            - secretRef:
                name: smtp-secret
