---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  POSTGRES_HOST: "postgres:5432"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  MEDIA_URL: "$MEDIA_URL"
  ZXCVBN_MINIMUM_SCORE: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-server-config
data:
  SKIP_DB_CREATE: "true"
  DB: postgresql # Database vendor
  DB_PORT: "5432" # Database port
  POSTGRES_SEEDS: postgres # Database server
  DBNAME: temporal
  VISIBILITY_DBNAME: temporal
  DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/production-sql.yml
  ENABLE_ES: "true"
  ES_SEEDS: elasticsearch
  ES_VERSION: v7 # Even though we run v8, temporal only has configuration for v7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-server-dynamic-config
data:
  empty: |
  yaml: |
    limit.maxIDLength:
      - value: 255
        constraints: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-client-config
data:
  TEMPORAL_ADDRESS: temporal:7233
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: background-worker-config
data:
  TEMPORAL_SHUTDOWN_GRACE_TIME: 1m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: process-upload-worker-config
data:
  TEMPORAL_SHUTDOWN_GRACE_TIME: 1h
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  cluster.routing.allocation.disk.threshold_enabled: "true"
  cluster.routing.allocation.disk.watermark.low: 512mb
  cluster.routing.allocation.disk.watermark.high: 256mb
  cluster.routing.allocation.disk.watermark.flood_stage: 128mb
  discovery.type: single-node
  ES_JAVA_OPTS: -Xms256m -Xmx256m
  xpack.security.enabled: "false"
