---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      restartPolicy: Always
      containers:
        - image: &gatewayImage registry.gitlab.com/letschurch/lets.church/gateway:latest
          name: gateway
          ports:
            - containerPort: 3000
          env: &gatewayEnv
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-letschurch
                  key: uri
            - name: IMGPROXY_KEY
              valueFrom:
                secretKeyRef:
                  name: imgproxy-secret
                  key: IMGPROXY_KEY
            - name: IMGPROXY_SALT
              valueFrom:
                secretKeyRef:
                  name: imgproxy-secret
                  key: IMGPROXY_SALT
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_GATEWAY_DSN
            - name: SERVICE_NAME
              value: gateway
          envFrom: &gatewayEnvFrom
            - configMapRef:
                name: gateway-config
            - configMapRef:
                name: temporal-client-config
            - secretRef:
                name: axiom-secret
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: mapbox-secret
            - secretRef:
                name: s3-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
      initContainers:
        - name: gateway-init-migrations
          image: *gatewayImage
          command: ["npm", "run", "prisma:migrate:deploy"]
          env: *gatewayEnv
          envFrom: *gatewayEnvFrom
        - name: gateway-init-es-mappings
          image: *gatewayImage
          command: ["npm", "run", "es:push-mappings"]
          env: *gatewayEnv
          envFrom: *gatewayEnvFrom
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
