---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-worker
  labels:
    app: import-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: import-worker
  template:
    metadata:
      labels:
        app: import-worker
    spec:
      restartPolicy: Always
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/import-worker:latest
          name: import-worker
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_IMPORT_WORKER_DSN
            - name: SERVICE_NAME
              value: import-worker
          envFrom:
            - configMapRef:
                name: temporal-client-config
            - configMapRef:
                name: import-worker-config
            - secretRef:
                name: axiom-secret
            - secretRef:
                name: s3-secret
