---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      restartPolicy: Always
      containers:
        - image: kibana:8.7.1
          name: kibana
          ports:
            - containerPort: 5601
          envFrom:
            - configMapRef:
                name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5601
