resources:
  - config.yml
  - gateway-deployment.yml
  - elasticsearch-deployment.yml
  - imgproxy-deployment.yml
  - kibana-deployment.yml
  - metabase-deployment.yml
  - pgweb-deployment.yml
  - temporal-deployment.yml
  - temporal-ui-deployment.yml
  - web-deployment.yml
  - web-next-deployment.yml
  - web-qwik-deployment.yml
  # Workers
  - background-worker-deployment.yml
  - background-low-priority-worker-deployment.yml
  - import-worker-deployment.yml
  - transcode-worker-deployment.yml
configMapGenerator:
  - name: web-config
    literals:
      - GRAPHQL_URL="http://gateway:3000/graphql"
  - name: web-next-config
    literals:
      - HOST="0.0.0.0"
  - name: gateway-config
    literals:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
      - IMGPROXY_URL="http://IMGPROXY_URL"
      - MEDIA_URL="http://MEDIA_URL"
      - POSTGRES_HOST="postgres:5432"
      - WEB_URL="https://lets.church"
      - ZXCVBN_MINIMUM_SCORE="3"
  - name: temporal-server-config
    literals:
      - SKIP_DB_CREATE="true"
      - DB=postgresql # Database vendor
      - SQL_TLS="true"
      - SQL_TLS_ENABLED="true" # https://github.com/temporalio/temporal/issues/2621
      - SQL_TLS_DISABLE_HOST_VERIFICATION="true"
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/production-sql.yml
      - ENABLE_ES="true"
      - ES_SEEDS=elasticsearch # ElasticSearch host
      - ES_VERSION=v7 # Even though we run v8, temporal only has configuration for v7
  - name: temporal-client-config
    literals:
      - TEMPORAL_ADDRESS=temporal:7233
  - name: temporal-ui-config
    literals:
      - TEMPORAL_UI_PORT=8080
  - name: kibana-config
    literals:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
  - name: background-low-priority-worker-config
    literals:
      - LC_QUEUE="background-low-priority"
  - name: background-worker-config
    literals:
      - TEMPORAL_SHUTDOWN_GRACE_TIME=1m
      - IDENTITY=(CLOUD1)
  - name: import-worker-config
    literals:
      - TEMPORAL_SHUTDOWN_GRACE_TIME=1m
      - IDENTITY=(CLOUD1)
  - name: transcode-worker-config
    literals:
      - TEMPORAL_SHUTDOWN_GRACE_TIME=1h
      - MAX_CONCURRENT_ACTIVITY_TASK_EXECUTIONS=1
      - IDENTITY=(CLOUD1)
  - name: elasticsearch-config
    literals:
      - cluster.routing.allocation.disk.threshold_enabled="true"
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS="-Xms256m -Xmx256m"
      - xpack.security.enabled="false"
