---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      restartPolicy: Always
      containers:
        - image: sosedoff/pgweb:0.14.1
          name: pgweb
          ports:
            - containerPort: 8081
          env:
            - name: PGWEB_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-letschurch
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
spec:
  selector:
    app: pgweb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
