---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-worker
  labels:
    app: probe-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: probe-worker
  template:
    metadata:
      labels:
        app: probe-worker
    spec:
      restartPolicy: Always
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/probe-worker:latest
          name: probe-worker
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_PROBE_WORKER_DSN
            - name: SERVICE_NAME
              value: probe-worker
          envFrom:
            - configMapRef:
                name: temporal-client-config
            - configMapRef:
                name: probe-worker-config
            - secretRef:
                name: axiom-secret
            - secretRef:
                name: s3-secret
