---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      restartPolicy: Always
      containers:
        - image: temporalio/ui:2.14.0
          name: temporal-ui
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: temporal-client-config
