---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      restartPolicy: Always
      containers:
        - image: temporalio/auto-setup:1.20.0.0
          name: temporal
          ports:
            - containerPort: 7233
          env:
            - name: POSTGRES_SEEDS
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-temporal
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-temporal
                  key: port
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-temporal
                  key: dbname
            - name: VISIBILITY_DBNAME
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-temporal
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-temporal
                  key: user
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: pg-pguser-temporal
                  key: password
          envFrom:
            - configMapRef:
                name: temporal-server-config
          volumeMounts:
            - name: temporal-dynamic-config
              mountPath: /etc/temporal/config/dynamicconfig
      volumes:
        - name: temporal-dynamic-config
          configMap:
            name: temporal-server-dynamic-config
            items:
              - key: yaml
                path: production-sql.yml
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7233
      targetPort: 7233
