---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcode-worker
  labels:
    app: transcode-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: transcode-worker
  template:
    metadata:
      labels:
        app: transcode-worker
    spec:
      restartPolicy: Always
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/transcode-worker:latest
          name: transcode-worker
          resources:
            requests:
              memory: 5Gi
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_TRANSCODE_WORKER_DSN
            - name: SERVICE_NAME
              value: transcode-worker
          envFrom:
            - configMapRef:
                name: temporal-client-config
            - configMapRef:
                name: transcode-worker-config
            - secretRef:
                name: axiom-secret
            - secretRef:
                name: s3-secret
