---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcribe-worker
  labels:
    app: transcribe-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: transcribe-worker
  template:
    metadata:
      labels:
        app: transcribe-worker
    spec:
      restartPolicy: Always
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/transcribe-worker:latest
          name: transcribe-worker
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_TRANSCRIBE_WORKER_DSN
            - name: SERVICE_NAME
              value: transcribe-worker
            - name: WHISPER_MODEL
              value: large-v2
          envFrom:
            - configMapRef:
                name: temporal-client-config
            - configMapRef:
                name: transcribe-worker-config
            - secretRef:
                name: axiom-pino-secret
            - secretRef:
                name: s3-ingest-secret
            - secretRef:
                name: s3-public-secret
