---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-next
  labels:
    app: web-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-next
  template:
    metadata:
      labels:
        app: web-next
    spec:
      restartPolicy: Always
      containers:
        - image: registry.gitlab.com/letschurch/lets.church/web-next:latest
          name: web-next
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_NAME
              value: web-next
          envFrom:
            - secretRef:
                name: turnstile-secret
            - configMapRef:
                name: web-config
            - secretRef:
                name: web-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-next
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: web-next
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
