extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
rules:
  import/order: error
  import/no-named-as-default: off
  import/no-unresolved: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/prefer-interface': off
