apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: letschurch-prod
resources:
  - ../base
  - postgres.yml
  - tunnel.yml
  - infisical-secrets.yml
configMapGenerator:
  - name: web-config
    behavior: merge
    literals:
      - IMGPROXY_URL="https://images.letschurch.cloud"
      - LISTMONK_INTERNAL_URL="http://listmonk"
      - MEDIA_URL="https://letschurch-media.b-cdn.net"
  - name: infisical-config
    literals:
      - projectSlug=letschurch-k8s-sq-fp
      - envSlug=prod
      - hostAPI=https://app.infisical.com/api
      - credentialsSecretName=infisical-universal-auth
      - credentialsSecretNamespace=letschurch-prod
      - managedSecretNamespace=letschurch-prod

generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      - op: add
        path: /spec/syncConfig
        value:
          resyncInterval: 60s
          instantUpdates: false
    target:
      kind: InfisicalSecret

replacements:
  - source:
      kind: ConfigMap
      name: infisical-config
      fieldPath: data.projectSlug
    targets:
      - select:
          kind: InfisicalSecret
        fieldPaths:
          - spec.authentication.universalAuth.secretsScope.projectSlug
  - source:
      kind: ConfigMap
      name: infisical-config
      fieldPath: data.envSlug
    targets:
      - select:
          kind: InfisicalSecret
        fieldPaths:
          - spec.authentication.universalAuth.secretsScope.envSlug
  - source:
      kind: ConfigMap
      name: infisical-config
      fieldPath: data.hostAPI
    targets:
      - select:
          kind: InfisicalSecret
        fieldPaths:
          - spec.hostAPI
  - source:
      kind: ConfigMap
      name: infisical-config
      fieldPath: data.credentialsSecretName
    targets:
      - select:
          kind: InfisicalSecret
        fieldPaths:
          - spec.authentication.universalAuth.credentialsRef.secretName
  - source:
      kind: ConfigMap
      name: infisical-config
      fieldPath: data.credentialsSecretNamespace
    targets:
      - select:
          kind: InfisicalSecret
        fieldPaths:
          - spec.authentication.universalAuth.credentialsRef.secretNamespace
  - source:
      kind: ConfigMap
      name: infisical-config
      fieldPath: data.managedSecretNamespace
    targets:
      - select:
          kind: InfisicalSecret
        fieldPaths:
          - spec.managedKubeSecretReferences.0.secretNamespace
