apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: letschurch-prod
resources:
  - ../base
  - postgres.yml
  - elasticsearch-pvc.crypt.yml
  - tunnel.yml
patches:
  - path: postgres-storage.crypt.yml
    target:
      kind: PostgresCluster
      name: pg
  - path: postgres-backup.crypt.yml
    target:
      kind: PostgresCluster
      name: pg
configMapGenerator:
  - name: web-config
    behavior: merge
    literals:
      - IMGPROXY_URL="https://images.letschurch.cloud"
      - LISTMONK_INTERNAL_URL="http://listmonk"
      - MEDIA_URL="https://letschurch-media.b-cdn.net"
secretGenerator:
  # Observability
  - name: axiom-pino-secret
    envs:
      - axiom-pino.crypt.env
  - name: vector-secret
    envs:
      - vector.crypt.env
  - name: sentry-secret
    envs:
      - sentry.crypt.env

  # Infrastructure
  - name: cloudflare-secret
    envs:
      - cloudflare.crypt.env
  - name: imgproxy-secret
    envs:
      - imgproxy.crypt.env
  - name: listmonk-secret
    envs:
      - listmonk.crypt.env
  - name: s3-ingest-secret
    envs:
      - s3-ingest.crypt.env
  - name: s3-public-secret
    envs:
      - s3-public.crypt.env
  - name: s3-backup-secret
    envs:
      - s3-backup.crypt.env
  - name: smtp-secret
    envs:
      - smtp.crypt.env
  - name: pgo-backup-creds
    files:
      - pgo-backup-creds.crypt.conf

  # Application
  - name: jwt-secret
    envs:
      - jwt.crypt.env
  - name: mapbox-secret
    envs:
      - mapbox.crypt.env
  - name: web-app-secret
    envs:
      - web-app.crypt.env

generatorOptions:
  disableNameSuffixHash: true
