# Required Secrets:
# JWT_SECRET

name = "media"
main = "src/index.ts"
compatibility_date = "2023-01-16"

r2_buckets = [{ binding = 'PUBLIC', bucket_name = 'letschurch-dev-public', preview_bucket_name = 'letschurch-dev-public' }]

[env.preview]
route = "media-preview.letschurch.cloud/*"
r2_buckets = [{ binding = 'PUBLIC', bucket_name = 'letschurch-dev-public', preview_bucket_name = 'letschurch-dev-public' }]
# TODO: separate buckets per environment
