import { createChatCompletionTracked } from '@letschurch/temporal/util/llm';
import { z } from 'zod';
import { cacheGetJson, cacheSetJson } from '@/util/cache';
import logger from '@/util/logger';

const moduleLogger = logger.child({
  module: 'trpc/media/suggested-questions',
});

// Per-video suggestions are stable for a given upload, so a day's TTL is plenty.
const QUESTIONS_CACHE_TTL_SECONDS = 60 * 60 * 24;

const MAX_QUESTIONS = 4;

const { OPENROUTER_VIDEO_QUESTIONS_MODEL } = z
  .object({
    // Same cheap/fast nano default as the other generators, with its own env so
    // per-video question generation can be tuned independently. The ANSWER is
    // generated by the mini agent; this only drafts the starter questions.
    OPENROUTER_VIDEO_QUESTIONS_MODEL: z.string().default('openai/gpt-5.4-nano'),
  })
  .parse(process.env);

const RawSchema = z.object({ questions: z.array(z.string()).nullable() });

const responseJsonSchema = {
  name: 'suggestedQuestions',
  strict: true,
  schema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      questions: { type: ['array', 'null'], items: { type: 'string' } },
    },
    required: ['questions'],
  },
} as const;

function systemPrompt(): string {
  return `You suggest starter questions for ONE specific video in a Christian sermon/teaching video library. Given the video's title, description, and summary, produce up to ${MAX_QUESTIONS} short, concrete questions a viewer is likely to want answered about THIS video.

Rules:
- Each question must be answerable from the video's own content (it is about this one video, not the whole library).
- Be specific to what this video actually covers — name its real subjects, people, passages, or arguments. Avoid generic questions that could apply to any sermon (bad: "What does the Bible say about grace?"; good: "Why does the speaker argue that ministry should be offered freely?").
- Each question must be FULLY SELF-CONTAINED and make sense on its own to someone who hasn't seen the other questions or the video. No anaphora ("this", "that principle"), no dangling fragments ("… explained").
- NEVER refer to a person with a pronoun ("he", "she", "they") or a bare role ("the speaker", "the author") — name them explicitly (e.g. "Conley Owens"). Bad: "Which licenses does he evaluate?"; good: "Which licenses does Conley Owens evaluate?".
- Keep each concise (a single natural question, ≈12 words or fewer where possible).
- Output ONLY the JSON object {"questions": [...]}.`;
}

/**
 * Generate per-video starter questions for the media-page "ask about this video"
 * dropdown, from the upload's title/description/summary, with gpt-5.4-nano.
 * Cached in Valkey by model + internal upload id (suggestions don't depend on the
 * date). Best-effort: any model/parse error resolves to an empty list. The LLM
 * call is recorded in `llm_call` (activity `videoSuggestedQuestions`).
 */
export async function generateSuggestedQuestions(
  uploadId: string,
  title: string | null,
  description: string | null,
  summary: string | null,
): Promise<string[]> {
  // Without at least a title there's nothing specific to ground questions in.
  if (!title) return [];

  const cacheKey = `video-questions:v1:${OPENROUTER_VIDEO_QUESTIONS_MODEL}:${uploadId}`;
  const cached = await cacheGetJson<string[]>(cacheKey);
  if (cached) return cached;

  const context = [
    `Title: ${title}`,
    summary ? `Summary: ${summary.slice(0, 2000)}` : null,
    !summary && description
      ? `Description: ${description.slice(0, 2000)}`
      : null,
  ]
    .filter(Boolean)
    .join('\n\n');

  try {
    const completion = await createChatCompletionTracked({
      model: OPENROUTER_VIDEO_QUESTIONS_MODEL,
      messages: [
        { role: 'system', content: systemPrompt() },
        { role: 'user', content: context },
      ],
      response_format: {
        type: 'json_schema',
        json_schema: responseJsonSchema,
      },
      tracking: { activity: 'videoSuggestedQuestions' },
    });

    const content = completion.choices[0]?.message.content ?? '';
    const cleaned = content
      .trim()
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/i, '');
    const raw = RawSchema.parse(JSON.parse(cleaned));
    const questions = (raw.questions ?? [])
      .map((s) => s.trim())
      .filter(Boolean)
      .slice(0, MAX_QUESTIONS);

    await cacheSetJson(cacheKey, questions, QUESTIONS_CACHE_TTL_SECONDS);
    return questions;
  } catch (err) {
    moduleLogger.warn(
      {
        context: {
          error: err instanceof Error ? err.message : String(err),
        },
      },
      'Suggested-questions generation failed',
    );
    return [];
  }
}
