/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard_'
import { Route as AuthRouteImport } from './routes/auth_'
import { Route as MainRouteImport } from './routes/_main'
import { Route as DashboardIndexRouteImport } from './routes/dashboard_/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as DashboardOrganizationsRouteImport } from './routes/dashboard_/organizations'
import { Route as DashboardChurchesRouteImport } from './routes/dashboard_/churches'
import { Route as DashboardChannelsRouteImport } from './routes/dashboard_/channels'
import { Route as DashboardAdminRouteImport } from './routes/dashboard_/admin'
import { Route as DashboardAccountRouteImport } from './routes/dashboard_/account'
import { Route as AuthRegisterRouteImport } from './routes/auth_/register'
import { Route as AuthLoginRouteImport } from './routes/auth_/login'
import { Route as MainFollowingRouteImport } from './routes/_main/following'
import { Route as MainMediaIndexRouteImport } from './routes/_main/media/index'
import { Route as DashboardOrganizationsOrgIdRouteImport } from './routes/dashboard_/organizations_.$orgId'
import { Route as DashboardChurchesNewRouteImport } from './routes/dashboard_/churches_.new'
import { Route as DashboardChurchesChurchIdRouteImport } from './routes/dashboard_/churches_.$churchId'
import { Route as DashboardChannelsNewRouteImport } from './routes/dashboard_/channels_.new'
import { Route as DashboardChannelsChannelIdRouteImport } from './routes/dashboard_/channels_.$channelId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard_/admin_.users'
import { Route as DashboardAdminProcessingUploadsRouteImport } from './routes/dashboard_/admin_.processing-uploads'
import { Route as DashboardAdminOrganizationTagsRouteImport } from './routes/dashboard_/admin_.organization-tags'
import { Route as DashboardAdminOrganizationApprovalsRouteImport } from './routes/dashboard_/admin_.organization-approvals'
import { Route as DashboardAdminChannelApprovalsRouteImport } from './routes/dashboard_/admin_.channel-approvals'
import { Route as DashboardAccountSecurityRouteImport } from './routes/dashboard_/account_.security'
import { Route as DashboardAccountProfileRouteImport } from './routes/dashboard_/account_.profile'
import { Route as DashboardOrganizationsOrgIdMembersRouteImport } from './routes/dashboard_/organizations_.$orgId_.members'
import { Route as DashboardOrganizationsOrgIdEditRouteImport } from './routes/dashboard_/organizations_.$orgId_.edit'
import { Route as DashboardOrganizationsOrgIdAssociationsRouteImport } from './routes/dashboard_/organizations_.$orgId_.associations'
import { Route as DashboardChurchesChurchIdMembersRouteImport } from './routes/dashboard_/churches_.$churchId_.members'
import { Route as DashboardChurchesChurchIdLeadersRouteImport } from './routes/dashboard_/churches_.$churchId_.leaders'
import { Route as DashboardChurchesChurchIdEditRouteImport } from './routes/dashboard_/churches_.$churchId_.edit'
import { Route as DashboardChurchesChurchIdChannelsRouteImport } from './routes/dashboard_/churches_.$churchId_.channels'
import { Route as DashboardChannelsChannelIdUploadsRouteImport } from './routes/dashboard_/channels_.$channelId_.uploads'
import { Route as DashboardChannelsChannelIdPlaylistsRouteImport } from './routes/dashboard_/channels_.$channelId_.playlists'
import { Route as DashboardChannelsChannelIdMembersRouteImport } from './routes/dashboard_/channels_.$channelId_.members'
import { Route as DashboardChannelsChannelIdEditRouteImport } from './routes/dashboard_/channels_.$channelId_.edit'
import { Route as DashboardChannelsChannelIdUploadsUploadIdRouteImport } from './routes/dashboard_/channels_.$channelId_.uploads_.$uploadId'
import { Route as DashboardChannelsChannelIdPlaylistsPlaylistIdRouteImport } from './routes/dashboard_/channels_.$channelId_.playlists_.$playlistId'
import { ServerRoute as TrpcSplatServerRouteImport } from './routes/trpc.$'
import { ServerRoute as AuthVerifyServerRouteImport } from './routes/auth_/verify'
import { ServerRoute as AuthLogoutServerRouteImport } from './routes/auth_/logout'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard_',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth_',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const DashboardOrganizationsRoute = DashboardOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChurchesRoute = DashboardChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainFollowingRoute = MainFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MainRoute,
} as any)
const MainMediaIndexRoute = MainMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => MainRoute,
} as any)
const DashboardOrganizationsOrgIdRoute =
  DashboardOrganizationsOrgIdRouteImport.update({
    id: '/organizations_/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesNewRoute = DashboardChurchesNewRouteImport.update({
  id: '/churches_/new',
  path: '/churches/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChurchesChurchIdRoute =
  DashboardChurchesChurchIdRouteImport.update({
    id: '/churches_/$churchId',
    path: '/churches/$churchId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsNewRoute = DashboardChannelsNewRouteImport.update({
  id: '/channels_/new',
  path: '/channels/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsChannelIdRoute =
  DashboardChannelsChannelIdRouteImport.update({
    id: '/channels_/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminProcessingUploadsRoute =
  DashboardAdminProcessingUploadsRouteImport.update({
    id: '/admin_/processing-uploads',
    path: '/admin/processing-uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOrganizationTagsRoute =
  DashboardAdminOrganizationTagsRouteImport.update({
    id: '/admin_/organization-tags',
    path: '/admin/organization-tags',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOrganizationApprovalsRoute =
  DashboardAdminOrganizationApprovalsRouteImport.update({
    id: '/admin_/organization-approvals',
    path: '/admin/organization-approvals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminChannelApprovalsRoute =
  DashboardAdminChannelApprovalsRouteImport.update({
    id: '/admin_/channel-approvals',
    path: '/admin/channel-approvals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountSecurityRoute =
  DashboardAccountSecurityRouteImport.update({
    id: '/account_/security',
    path: '/account/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountProfileRoute = DashboardAccountProfileRouteImport.update({
  id: '/account_/profile',
  path: '/account/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationsOrgIdMembersRoute =
  DashboardOrganizationsOrgIdMembersRouteImport.update({
    id: '/organizations_/$orgId_/members',
    path: '/organizations/$orgId/members',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationsOrgIdEditRoute =
  DashboardOrganizationsOrgIdEditRouteImport.update({
    id: '/organizations_/$orgId_/edit',
    path: '/organizations/$orgId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationsOrgIdAssociationsRoute =
  DashboardOrganizationsOrgIdAssociationsRouteImport.update({
    id: '/organizations_/$orgId_/associations',
    path: '/organizations/$orgId/associations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdMembersRoute =
  DashboardChurchesChurchIdMembersRouteImport.update({
    id: '/churches_/$churchId_/members',
    path: '/churches/$churchId/members',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdLeadersRoute =
  DashboardChurchesChurchIdLeadersRouteImport.update({
    id: '/churches_/$churchId_/leaders',
    path: '/churches/$churchId/leaders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdEditRoute =
  DashboardChurchesChurchIdEditRouteImport.update({
    id: '/churches_/$churchId_/edit',
    path: '/churches/$churchId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChurchesChurchIdChannelsRoute =
  DashboardChurchesChurchIdChannelsRouteImport.update({
    id: '/churches_/$churchId_/channels',
    path: '/churches/$churchId/channels',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdUploadsRoute =
  DashboardChannelsChannelIdUploadsRouteImport.update({
    id: '/channels_/$channelId_/uploads',
    path: '/channels/$channelId/uploads',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdPlaylistsRoute =
  DashboardChannelsChannelIdPlaylistsRouteImport.update({
    id: '/channels_/$channelId_/playlists',
    path: '/channels/$channelId/playlists',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdMembersRoute =
  DashboardChannelsChannelIdMembersRouteImport.update({
    id: '/channels_/$channelId_/members',
    path: '/channels/$channelId/members',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdEditRoute =
  DashboardChannelsChannelIdEditRouteImport.update({
    id: '/channels_/$channelId_/edit',
    path: '/channels/$channelId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdUploadsUploadIdRoute =
  DashboardChannelsChannelIdUploadsUploadIdRouteImport.update({
    id: '/channels_/$channelId_/uploads_/$uploadId',
    path: '/channels/$channelId/uploads/$uploadId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdPlaylistsPlaylistIdRoute =
  DashboardChannelsChannelIdPlaylistsPlaylistIdRouteImport.update({
    id: '/channels_/$channelId_/playlists_/$playlistId',
    path: '/channels/$channelId/playlists/$playlistId',
    getParentRoute: () => DashboardRoute,
  } as any)
const TrpcSplatServerRoute = TrpcSplatServerRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const AuthVerifyServerRoute = AuthVerifyServerRouteImport.update({
  id: '/auth_/verify',
  path: '/auth/verify',
  getParentRoute: () => rootServerRouteImport,
} as any)
const AuthLogoutServerRoute = AuthLogoutServerRouteImport.update({
  id: '/auth_/logout',
  path: '/auth/logout',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/following': typeof MainFollowingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/churches': typeof DashboardChurchesRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/': typeof MainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/security': typeof DashboardAccountSecurityRoute
  '/dashboard/admin/channel-approvals': typeof DashboardAdminChannelApprovalsRoute
  '/dashboard/admin/organization-approvals': typeof DashboardAdminOrganizationApprovalsRoute
  '/dashboard/admin/organization-tags': typeof DashboardAdminOrganizationTagsRoute
  '/dashboard/admin/processing-uploads': typeof DashboardAdminProcessingUploadsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/channels/new': typeof DashboardChannelsNewRoute
  '/dashboard/churches/$churchId': typeof DashboardChurchesChurchIdRoute
  '/dashboard/churches/new': typeof DashboardChurchesNewRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/media': typeof MainMediaIndexRoute
  '/dashboard/channels/$channelId/edit': typeof DashboardChannelsChannelIdEditRoute
  '/dashboard/channels/$channelId/members': typeof DashboardChannelsChannelIdMembersRoute
  '/dashboard/channels/$channelId/playlists': typeof DashboardChannelsChannelIdPlaylistsRoute
  '/dashboard/channels/$channelId/uploads': typeof DashboardChannelsChannelIdUploadsRoute
  '/dashboard/churches/$churchId/channels': typeof DashboardChurchesChurchIdChannelsRoute
  '/dashboard/churches/$churchId/edit': typeof DashboardChurchesChurchIdEditRoute
  '/dashboard/churches/$churchId/leaders': typeof DashboardChurchesChurchIdLeadersRoute
  '/dashboard/churches/$churchId/members': typeof DashboardChurchesChurchIdMembersRoute
  '/dashboard/organizations/$orgId/associations': typeof DashboardOrganizationsOrgIdAssociationsRoute
  '/dashboard/organizations/$orgId/edit': typeof DashboardOrganizationsOrgIdEditRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/channels/$channelId/playlists/$playlistId': typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  '/dashboard/channels/$channelId/uploads/$uploadId': typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/following': typeof MainFollowingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/churches': typeof DashboardChurchesRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/security': typeof DashboardAccountSecurityRoute
  '/dashboard/admin/channel-approvals': typeof DashboardAdminChannelApprovalsRoute
  '/dashboard/admin/organization-approvals': typeof DashboardAdminOrganizationApprovalsRoute
  '/dashboard/admin/organization-tags': typeof DashboardAdminOrganizationTagsRoute
  '/dashboard/admin/processing-uploads': typeof DashboardAdminProcessingUploadsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/channels/new': typeof DashboardChannelsNewRoute
  '/dashboard/churches/$churchId': typeof DashboardChurchesChurchIdRoute
  '/dashboard/churches/new': typeof DashboardChurchesNewRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/media': typeof MainMediaIndexRoute
  '/dashboard/channels/$channelId/edit': typeof DashboardChannelsChannelIdEditRoute
  '/dashboard/channels/$channelId/members': typeof DashboardChannelsChannelIdMembersRoute
  '/dashboard/channels/$channelId/playlists': typeof DashboardChannelsChannelIdPlaylistsRoute
  '/dashboard/channels/$channelId/uploads': typeof DashboardChannelsChannelIdUploadsRoute
  '/dashboard/churches/$churchId/channels': typeof DashboardChurchesChurchIdChannelsRoute
  '/dashboard/churches/$churchId/edit': typeof DashboardChurchesChurchIdEditRoute
  '/dashboard/churches/$churchId/leaders': typeof DashboardChurchesChurchIdLeadersRoute
  '/dashboard/churches/$churchId/members': typeof DashboardChurchesChurchIdMembersRoute
  '/dashboard/organizations/$orgId/associations': typeof DashboardOrganizationsOrgIdAssociationsRoute
  '/dashboard/organizations/$orgId/edit': typeof DashboardOrganizationsOrgIdEditRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/channels/$channelId/playlists/$playlistId': typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  '/dashboard/channels/$channelId/uploads/$uploadId': typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/auth_': typeof AuthRouteWithChildren
  '/dashboard_': typeof DashboardRouteWithChildren
  '/_main/following': typeof MainFollowingRoute
  '/auth_/login': typeof AuthLoginRoute
  '/auth_/register': typeof AuthRegisterRoute
  '/dashboard_/account': typeof DashboardAccountRoute
  '/dashboard_/admin': typeof DashboardAdminRoute
  '/dashboard_/channels': typeof DashboardChannelsRoute
  '/dashboard_/churches': typeof DashboardChurchesRoute
  '/dashboard_/organizations': typeof DashboardOrganizationsRoute
  '/_main/': typeof MainIndexRoute
  '/dashboard_/': typeof DashboardIndexRoute
  '/dashboard_/account_/profile': typeof DashboardAccountProfileRoute
  '/dashboard_/account_/security': typeof DashboardAccountSecurityRoute
  '/dashboard_/admin_/channel-approvals': typeof DashboardAdminChannelApprovalsRoute
  '/dashboard_/admin_/organization-approvals': typeof DashboardAdminOrganizationApprovalsRoute
  '/dashboard_/admin_/organization-tags': typeof DashboardAdminOrganizationTagsRoute
  '/dashboard_/admin_/processing-uploads': typeof DashboardAdminProcessingUploadsRoute
  '/dashboard_/admin_/users': typeof DashboardAdminUsersRoute
  '/dashboard_/channels_/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard_/channels_/new': typeof DashboardChannelsNewRoute
  '/dashboard_/churches_/$churchId': typeof DashboardChurchesChurchIdRoute
  '/dashboard_/churches_/new': typeof DashboardChurchesNewRoute
  '/dashboard_/organizations_/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/_main/media/': typeof MainMediaIndexRoute
  '/dashboard_/channels_/$channelId_/edit': typeof DashboardChannelsChannelIdEditRoute
  '/dashboard_/channels_/$channelId_/members': typeof DashboardChannelsChannelIdMembersRoute
  '/dashboard_/channels_/$channelId_/playlists': typeof DashboardChannelsChannelIdPlaylistsRoute
  '/dashboard_/channels_/$channelId_/uploads': typeof DashboardChannelsChannelIdUploadsRoute
  '/dashboard_/churches_/$churchId_/channels': typeof DashboardChurchesChurchIdChannelsRoute
  '/dashboard_/churches_/$churchId_/edit': typeof DashboardChurchesChurchIdEditRoute
  '/dashboard_/churches_/$churchId_/leaders': typeof DashboardChurchesChurchIdLeadersRoute
  '/dashboard_/churches_/$churchId_/members': typeof DashboardChurchesChurchIdMembersRoute
  '/dashboard_/organizations_/$orgId_/associations': typeof DashboardOrganizationsOrgIdAssociationsRoute
  '/dashboard_/organizations_/$orgId_/edit': typeof DashboardOrganizationsOrgIdEditRoute
  '/dashboard_/organizations_/$orgId_/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard_/channels_/$channelId_/playlists_/$playlistId': typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  '/dashboard_/channels_/$channelId_/uploads_/$uploadId': typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/following'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/channels'
    | '/dashboard/churches'
    | '/dashboard/organizations'
    | '/'
    | '/dashboard/'
    | '/dashboard/account/profile'
    | '/dashboard/account/security'
    | '/dashboard/admin/channel-approvals'
    | '/dashboard/admin/organization-approvals'
    | '/dashboard/admin/organization-tags'
    | '/dashboard/admin/processing-uploads'
    | '/dashboard/admin/users'
    | '/dashboard/channels/$channelId'
    | '/dashboard/channels/new'
    | '/dashboard/churches/$churchId'
    | '/dashboard/churches/new'
    | '/dashboard/organizations/$orgId'
    | '/media'
    | '/dashboard/channels/$channelId/edit'
    | '/dashboard/channels/$channelId/members'
    | '/dashboard/channels/$channelId/playlists'
    | '/dashboard/channels/$channelId/uploads'
    | '/dashboard/churches/$churchId/channels'
    | '/dashboard/churches/$churchId/edit'
    | '/dashboard/churches/$churchId/leaders'
    | '/dashboard/churches/$churchId/members'
    | '/dashboard/organizations/$orgId/associations'
    | '/dashboard/organizations/$orgId/edit'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/channels/$channelId/playlists/$playlistId'
    | '/dashboard/channels/$channelId/uploads/$uploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/following'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/channels'
    | '/dashboard/churches'
    | '/dashboard/organizations'
    | '/'
    | '/dashboard'
    | '/dashboard/account/profile'
    | '/dashboard/account/security'
    | '/dashboard/admin/channel-approvals'
    | '/dashboard/admin/organization-approvals'
    | '/dashboard/admin/organization-tags'
    | '/dashboard/admin/processing-uploads'
    | '/dashboard/admin/users'
    | '/dashboard/channels/$channelId'
    | '/dashboard/channels/new'
    | '/dashboard/churches/$churchId'
    | '/dashboard/churches/new'
    | '/dashboard/organizations/$orgId'
    | '/media'
    | '/dashboard/channels/$channelId/edit'
    | '/dashboard/channels/$channelId/members'
    | '/dashboard/channels/$channelId/playlists'
    | '/dashboard/channels/$channelId/uploads'
    | '/dashboard/churches/$churchId/channels'
    | '/dashboard/churches/$churchId/edit'
    | '/dashboard/churches/$churchId/leaders'
    | '/dashboard/churches/$churchId/members'
    | '/dashboard/organizations/$orgId/associations'
    | '/dashboard/organizations/$orgId/edit'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/channels/$channelId/playlists/$playlistId'
    | '/dashboard/channels/$channelId/uploads/$uploadId'
  id:
    | '__root__'
    | '/_main'
    | '/auth_'
    | '/dashboard_'
    | '/_main/following'
    | '/auth_/login'
    | '/auth_/register'
    | '/dashboard_/account'
    | '/dashboard_/admin'
    | '/dashboard_/channels'
    | '/dashboard_/churches'
    | '/dashboard_/organizations'
    | '/_main/'
    | '/dashboard_/'
    | '/dashboard_/account_/profile'
    | '/dashboard_/account_/security'
    | '/dashboard_/admin_/channel-approvals'
    | '/dashboard_/admin_/organization-approvals'
    | '/dashboard_/admin_/organization-tags'
    | '/dashboard_/admin_/processing-uploads'
    | '/dashboard_/admin_/users'
    | '/dashboard_/channels_/$channelId'
    | '/dashboard_/channels_/new'
    | '/dashboard_/churches_/$churchId'
    | '/dashboard_/churches_/new'
    | '/dashboard_/organizations_/$orgId'
    | '/_main/media/'
    | '/dashboard_/channels_/$channelId_/edit'
    | '/dashboard_/channels_/$channelId_/members'
    | '/dashboard_/channels_/$channelId_/playlists'
    | '/dashboard_/channels_/$channelId_/uploads'
    | '/dashboard_/churches_/$churchId_/channels'
    | '/dashboard_/churches_/$churchId_/edit'
    | '/dashboard_/churches_/$churchId_/leaders'
    | '/dashboard_/churches_/$churchId_/members'
    | '/dashboard_/organizations_/$orgId_/associations'
    | '/dashboard_/organizations_/$orgId_/edit'
    | '/dashboard_/organizations_/$orgId_/members'
    | '/dashboard_/channels_/$channelId_/playlists_/$playlistId'
    | '/dashboard_/channels_/$channelId_/uploads_/$uploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/auth/logout': typeof AuthLogoutServerRoute
  '/auth/verify': typeof AuthVerifyServerRoute
  '/trpc/$': typeof TrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/auth/logout': typeof AuthLogoutServerRoute
  '/auth/verify': typeof AuthVerifyServerRoute
  '/trpc/$': typeof TrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/auth_/logout': typeof AuthLogoutServerRoute
  '/auth_/verify': typeof AuthVerifyServerRoute
  '/trpc/$': typeof TrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/auth/logout' | '/auth/verify' | '/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/auth/logout' | '/auth/verify' | '/trpc/$'
  id: '__root__' | '/auth_/logout' | '/auth_/verify' | '/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  AuthLogoutServerRoute: typeof AuthLogoutServerRoute
  AuthVerifyServerRoute: typeof AuthVerifyServerRoute
  TrpcSplatServerRoute: typeof TrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard_': {
      id: '/dashboard_'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_': {
      id: '/auth_'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/': {
      id: '/dashboard_/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard_/organizations': {
      id: '/dashboard_/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches': {
      id: '/dashboard_/churches'
      path: '/churches'
      fullPath: '/dashboard/churches'
      preLoaderRoute: typeof DashboardChurchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels': {
      id: '/dashboard_/channels'
      path: '/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin': {
      id: '/dashboard_/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account': {
      id: '/dashboard_/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth_/register': {
      id: '/auth_/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/login': {
      id: '/auth_/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/following': {
      id: '/_main/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof MainFollowingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/media/': {
      id: '/_main/media/'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MainMediaIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard_/organizations_/$orgId': {
      id: '/dashboard_/organizations_/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/dashboard/organizations/$orgId'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/new': {
      id: '/dashboard_/churches_/new'
      path: '/churches/new'
      fullPath: '/dashboard/churches/new'
      preLoaderRoute: typeof DashboardChurchesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId': {
      id: '/dashboard_/churches_/$churchId'
      path: '/churches/$churchId'
      fullPath: '/dashboard/churches/$churchId'
      preLoaderRoute: typeof DashboardChurchesChurchIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/new': {
      id: '/dashboard_/channels_/new'
      path: '/channels/new'
      fullPath: '/dashboard/channels/new'
      preLoaderRoute: typeof DashboardChannelsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId': {
      id: '/dashboard_/channels_/$channelId'
      path: '/channels/$channelId'
      fullPath: '/dashboard/channels/$channelId'
      preLoaderRoute: typeof DashboardChannelsChannelIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/users': {
      id: '/dashboard_/admin_/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/processing-uploads': {
      id: '/dashboard_/admin_/processing-uploads'
      path: '/admin/processing-uploads'
      fullPath: '/dashboard/admin/processing-uploads'
      preLoaderRoute: typeof DashboardAdminProcessingUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/organization-tags': {
      id: '/dashboard_/admin_/organization-tags'
      path: '/admin/organization-tags'
      fullPath: '/dashboard/admin/organization-tags'
      preLoaderRoute: typeof DashboardAdminOrganizationTagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/organization-approvals': {
      id: '/dashboard_/admin_/organization-approvals'
      path: '/admin/organization-approvals'
      fullPath: '/dashboard/admin/organization-approvals'
      preLoaderRoute: typeof DashboardAdminOrganizationApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/admin_/channel-approvals': {
      id: '/dashboard_/admin_/channel-approvals'
      path: '/admin/channel-approvals'
      fullPath: '/dashboard/admin/channel-approvals'
      preLoaderRoute: typeof DashboardAdminChannelApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account_/security': {
      id: '/dashboard_/account_/security'
      path: '/account/security'
      fullPath: '/dashboard/account/security'
      preLoaderRoute: typeof DashboardAccountSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account_/profile': {
      id: '/dashboard_/account_/profile'
      path: '/account/profile'
      fullPath: '/dashboard/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/organizations_/$orgId_/members': {
      id: '/dashboard_/organizations_/$orgId_/members'
      path: '/organizations/$orgId/members'
      fullPath: '/dashboard/organizations/$orgId/members'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/organizations_/$orgId_/edit': {
      id: '/dashboard_/organizations_/$orgId_/edit'
      path: '/organizations/$orgId/edit'
      fullPath: '/dashboard/organizations/$orgId/edit'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/organizations_/$orgId_/associations': {
      id: '/dashboard_/organizations_/$orgId_/associations'
      path: '/organizations/$orgId/associations'
      fullPath: '/dashboard/organizations/$orgId/associations'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdAssociationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/members': {
      id: '/dashboard_/churches_/$churchId_/members'
      path: '/churches/$churchId/members'
      fullPath: '/dashboard/churches/$churchId/members'
      preLoaderRoute: typeof DashboardChurchesChurchIdMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/leaders': {
      id: '/dashboard_/churches_/$churchId_/leaders'
      path: '/churches/$churchId/leaders'
      fullPath: '/dashboard/churches/$churchId/leaders'
      preLoaderRoute: typeof DashboardChurchesChurchIdLeadersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/edit': {
      id: '/dashboard_/churches_/$churchId_/edit'
      path: '/churches/$churchId/edit'
      fullPath: '/dashboard/churches/$churchId/edit'
      preLoaderRoute: typeof DashboardChurchesChurchIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/churches_/$churchId_/channels': {
      id: '/dashboard_/churches_/$churchId_/channels'
      path: '/churches/$churchId/channels'
      fullPath: '/dashboard/churches/$churchId/channels'
      preLoaderRoute: typeof DashboardChurchesChurchIdChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/uploads': {
      id: '/dashboard_/channels_/$channelId_/uploads'
      path: '/channels/$channelId/uploads'
      fullPath: '/dashboard/channels/$channelId/uploads'
      preLoaderRoute: typeof DashboardChannelsChannelIdUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/playlists': {
      id: '/dashboard_/channels_/$channelId_/playlists'
      path: '/channels/$channelId/playlists'
      fullPath: '/dashboard/channels/$channelId/playlists'
      preLoaderRoute: typeof DashboardChannelsChannelIdPlaylistsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/members': {
      id: '/dashboard_/channels_/$channelId_/members'
      path: '/channels/$channelId/members'
      fullPath: '/dashboard/channels/$channelId/members'
      preLoaderRoute: typeof DashboardChannelsChannelIdMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/edit': {
      id: '/dashboard_/channels_/$channelId_/edit'
      path: '/channels/$channelId/edit'
      fullPath: '/dashboard/channels/$channelId/edit'
      preLoaderRoute: typeof DashboardChannelsChannelIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/uploads_/$uploadId': {
      id: '/dashboard_/channels_/$channelId_/uploads_/$uploadId'
      path: '/channels/$channelId/uploads/$uploadId'
      fullPath: '/dashboard/channels/$channelId/uploads/$uploadId'
      preLoaderRoute: typeof DashboardChannelsChannelIdUploadsUploadIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId_/playlists_/$playlistId': {
      id: '/dashboard_/channels_/$channelId_/playlists_/$playlistId'
      path: '/channels/$channelId/playlists/$playlistId'
      fullPath: '/dashboard/channels/$channelId/playlists/$playlistId'
      preLoaderRoute: typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/auth_/verify': {
      id: '/auth_/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/auth_/logout': {
      id: '/auth_/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface MainRouteChildren {
  MainFollowingRoute: typeof MainFollowingRoute
  MainIndexRoute: typeof MainIndexRoute
  MainMediaIndexRoute: typeof MainMediaIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainFollowingRoute: MainFollowingRoute,
  MainIndexRoute: MainIndexRoute,
  MainMediaIndexRoute: MainMediaIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardChannelsRoute: typeof DashboardChannelsRoute
  DashboardChurchesRoute: typeof DashboardChurchesRoute
  DashboardOrganizationsRoute: typeof DashboardOrganizationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountSecurityRoute: typeof DashboardAccountSecurityRoute
  DashboardAdminChannelApprovalsRoute: typeof DashboardAdminChannelApprovalsRoute
  DashboardAdminOrganizationApprovalsRoute: typeof DashboardAdminOrganizationApprovalsRoute
  DashboardAdminOrganizationTagsRoute: typeof DashboardAdminOrganizationTagsRoute
  DashboardAdminProcessingUploadsRoute: typeof DashboardAdminProcessingUploadsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardChannelsChannelIdRoute: typeof DashboardChannelsChannelIdRoute
  DashboardChannelsNewRoute: typeof DashboardChannelsNewRoute
  DashboardChurchesChurchIdRoute: typeof DashboardChurchesChurchIdRoute
  DashboardChurchesNewRoute: typeof DashboardChurchesNewRoute
  DashboardOrganizationsOrgIdRoute: typeof DashboardOrganizationsOrgIdRoute
  DashboardChannelsChannelIdEditRoute: typeof DashboardChannelsChannelIdEditRoute
  DashboardChannelsChannelIdMembersRoute: typeof DashboardChannelsChannelIdMembersRoute
  DashboardChannelsChannelIdPlaylistsRoute: typeof DashboardChannelsChannelIdPlaylistsRoute
  DashboardChannelsChannelIdUploadsRoute: typeof DashboardChannelsChannelIdUploadsRoute
  DashboardChurchesChurchIdChannelsRoute: typeof DashboardChurchesChurchIdChannelsRoute
  DashboardChurchesChurchIdEditRoute: typeof DashboardChurchesChurchIdEditRoute
  DashboardChurchesChurchIdLeadersRoute: typeof DashboardChurchesChurchIdLeadersRoute
  DashboardChurchesChurchIdMembersRoute: typeof DashboardChurchesChurchIdMembersRoute
  DashboardOrganizationsOrgIdAssociationsRoute: typeof DashboardOrganizationsOrgIdAssociationsRoute
  DashboardOrganizationsOrgIdEditRoute: typeof DashboardOrganizationsOrgIdEditRoute
  DashboardOrganizationsOrgIdMembersRoute: typeof DashboardOrganizationsOrgIdMembersRoute
  DashboardChannelsChannelIdPlaylistsPlaylistIdRoute: typeof DashboardChannelsChannelIdPlaylistsPlaylistIdRoute
  DashboardChannelsChannelIdUploadsUploadIdRoute: typeof DashboardChannelsChannelIdUploadsUploadIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardChannelsRoute: DashboardChannelsRoute,
  DashboardChurchesRoute: DashboardChurchesRoute,
  DashboardOrganizationsRoute: DashboardOrganizationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountSecurityRoute: DashboardAccountSecurityRoute,
  DashboardAdminChannelApprovalsRoute: DashboardAdminChannelApprovalsRoute,
  DashboardAdminOrganizationApprovalsRoute:
    DashboardAdminOrganizationApprovalsRoute,
  DashboardAdminOrganizationTagsRoute: DashboardAdminOrganizationTagsRoute,
  DashboardAdminProcessingUploadsRoute: DashboardAdminProcessingUploadsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardChannelsChannelIdRoute: DashboardChannelsChannelIdRoute,
  DashboardChannelsNewRoute: DashboardChannelsNewRoute,
  DashboardChurchesChurchIdRoute: DashboardChurchesChurchIdRoute,
  DashboardChurchesNewRoute: DashboardChurchesNewRoute,
  DashboardOrganizationsOrgIdRoute: DashboardOrganizationsOrgIdRoute,
  DashboardChannelsChannelIdEditRoute: DashboardChannelsChannelIdEditRoute,
  DashboardChannelsChannelIdMembersRoute:
    DashboardChannelsChannelIdMembersRoute,
  DashboardChannelsChannelIdPlaylistsRoute:
    DashboardChannelsChannelIdPlaylistsRoute,
  DashboardChannelsChannelIdUploadsRoute:
    DashboardChannelsChannelIdUploadsRoute,
  DashboardChurchesChurchIdChannelsRoute:
    DashboardChurchesChurchIdChannelsRoute,
  DashboardChurchesChurchIdEditRoute: DashboardChurchesChurchIdEditRoute,
  DashboardChurchesChurchIdLeadersRoute: DashboardChurchesChurchIdLeadersRoute,
  DashboardChurchesChurchIdMembersRoute: DashboardChurchesChurchIdMembersRoute,
  DashboardOrganizationsOrgIdAssociationsRoute:
    DashboardOrganizationsOrgIdAssociationsRoute,
  DashboardOrganizationsOrgIdEditRoute: DashboardOrganizationsOrgIdEditRoute,
  DashboardOrganizationsOrgIdMembersRoute:
    DashboardOrganizationsOrgIdMembersRoute,
  DashboardChannelsChannelIdPlaylistsPlaylistIdRoute:
    DashboardChannelsChannelIdPlaylistsPlaylistIdRoute,
  DashboardChannelsChannelIdUploadsUploadIdRoute:
    DashboardChannelsChannelIdUploadsUploadIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  AuthLogoutServerRoute: AuthLogoutServerRoute,
  AuthVerifyServerRoute: AuthVerifyServerRoute,
  TrpcSplatServerRoute: TrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
