/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard_'
import { Route as AuthRouteImport } from './routes/auth_'
import { Route as MainRouteImport } from './routes/_main'
import { Route as DashboardIndexRouteImport } from './routes/dashboard_/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as DashboardChurchesRouteImport } from './routes/dashboard_/churches'
import { Route as DashboardChannelsRouteImport } from './routes/dashboard_/channels'
import { Route as DashboardAccountRouteImport } from './routes/dashboard_/account'
import { Route as AuthRegisterRouteImport } from './routes/auth_/register'
import { Route as AuthLoginRouteImport } from './routes/auth_/login'
import { Route as MainMediaIndexRouteImport } from './routes/_main/media/index'
import { Route as DashboardChurchesChurchIdRouteImport } from './routes/dashboard_/churches_.$churchId'
import { Route as DashboardChannelsChannelIdRouteImport } from './routes/dashboard_/channels_.$channelId'
import { ServerRoute as AuthVerifyServerRouteImport } from './routes/auth_/verify'
import { ServerRoute as AuthLogoutServerRouteImport } from './routes/auth_/logout'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard_',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth_',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const DashboardChurchesRoute = DashboardChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainMediaIndexRoute = MainMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => MainRoute,
} as any)
const DashboardChurchesChurchIdRoute =
  DashboardChurchesChurchIdRouteImport.update({
    id: '/churches_/$churchId',
    path: '/churches/$churchId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdRoute =
  DashboardChannelsChannelIdRouteImport.update({
    id: '/channels_/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthVerifyServerRoute = AuthVerifyServerRouteImport.update({
  id: '/auth_/verify',
  path: '/auth/verify',
  getParentRoute: () => rootServerRouteImport,
} as any)
const AuthLogoutServerRoute = AuthLogoutServerRouteImport.update({
  id: '/auth_/logout',
  path: '/auth/logout',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/churches': typeof DashboardChurchesRoute
  '/': typeof MainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/churches/$churchId': typeof DashboardChurchesChurchIdRoute
  '/media': typeof MainMediaIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/churches': typeof DashboardChurchesRoute
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/churches/$churchId': typeof DashboardChurchesChurchIdRoute
  '/media': typeof MainMediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/auth_': typeof AuthRouteWithChildren
  '/dashboard_': typeof DashboardRouteWithChildren
  '/auth_/login': typeof AuthLoginRoute
  '/auth_/register': typeof AuthRegisterRoute
  '/dashboard_/account': typeof DashboardAccountRoute
  '/dashboard_/channels': typeof DashboardChannelsRoute
  '/dashboard_/churches': typeof DashboardChurchesRoute
  '/_main/': typeof MainIndexRoute
  '/dashboard_/': typeof DashboardIndexRoute
  '/dashboard_/channels_/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard_/churches_/$churchId': typeof DashboardChurchesChurchIdRoute
  '/_main/media/': typeof MainMediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/channels'
    | '/dashboard/churches'
    | '/'
    | '/dashboard/'
    | '/dashboard/channels/$channelId'
    | '/dashboard/churches/$churchId'
    | '/media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/channels'
    | '/dashboard/churches'
    | '/'
    | '/dashboard'
    | '/dashboard/channels/$channelId'
    | '/dashboard/churches/$churchId'
    | '/media'
  id:
    | '__root__'
    | '/_main'
    | '/auth_'
    | '/dashboard_'
    | '/auth_/login'
    | '/auth_/register'
    | '/dashboard_/account'
    | '/dashboard_/channels'
    | '/dashboard_/churches'
    | '/_main/'
    | '/dashboard_/'
    | '/dashboard_/channels_/$channelId'
    | '/dashboard_/churches_/$churchId'
    | '/_main/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/auth/logout': typeof AuthLogoutServerRoute
  '/auth/verify': typeof AuthVerifyServerRoute
}
export interface FileServerRoutesByTo {
  '/auth/logout': typeof AuthLogoutServerRoute
  '/auth/verify': typeof AuthVerifyServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/auth_/logout': typeof AuthLogoutServerRoute
  '/auth_/verify': typeof AuthVerifyServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/auth/logout' | '/auth/verify'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/auth/logout' | '/auth/verify'
  id: '__root__' | '/auth_/logout' | '/auth_/verify'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  AuthLogoutServerRoute: typeof AuthLogoutServerRoute
  AuthVerifyServerRoute: typeof AuthVerifyServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard_': {
      id: '/dashboard_'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_': {
      id: '/auth_'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/': {
      id: '/dashboard_/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard_/churches': {
      id: '/dashboard_/churches'
      path: '/churches'
      fullPath: '/dashboard/churches'
      preLoaderRoute: typeof DashboardChurchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels': {
      id: '/dashboard_/channels'
      path: '/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/account': {
      id: '/dashboard_/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth_/register': {
      id: '/auth_/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth_/login': {
      id: '/auth_/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/media/': {
      id: '/_main/media/'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MainMediaIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard_/churches_/$churchId': {
      id: '/dashboard_/churches_/$churchId'
      path: '/churches/$churchId'
      fullPath: '/dashboard/churches/$churchId'
      preLoaderRoute: typeof DashboardChurchesChurchIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard_/channels_/$channelId': {
      id: '/dashboard_/channels_/$channelId'
      path: '/channels/$channelId'
      fullPath: '/dashboard/channels/$channelId'
      preLoaderRoute: typeof DashboardChannelsChannelIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/auth_/verify': {
      id: '/auth_/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/auth_/logout': {
      id: '/auth_/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainMediaIndexRoute: typeof MainMediaIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainMediaIndexRoute: MainMediaIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardChannelsRoute: typeof DashboardChannelsRoute
  DashboardChurchesRoute: typeof DashboardChurchesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChannelsChannelIdRoute: typeof DashboardChannelsChannelIdRoute
  DashboardChurchesChurchIdRoute: typeof DashboardChurchesChurchIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardChannelsRoute: DashboardChannelsRoute,
  DashboardChurchesRoute: DashboardChurchesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChannelsChannelIdRoute: DashboardChannelsChannelIdRoute,
  DashboardChurchesChurchIdRoute: DashboardChurchesChurchIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  AuthLogoutServerRoute: AuthLogoutServerRoute,
  AuthVerifyServerRoute: AuthVerifyServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
