---
- name: Setup probe worker
  hosts: probe-workers
  become: true
  vars_files:
    - ../variables/probe-worker.yml
  pre_tasks:
    - name: Login to Infisical
      infisical.vault.login:
        url: https://app.infisical.com
        auth_method: universal_auth
        universal_auth_client_id: "{{ lookup('env', 'INFISICAL_CLIENT_ID') }}"
        universal_auth_client_secret: "{{ lookup('env', 'INFISICAL_CLIENT_SECRET') }}"
      register: infisical_login
    - name: Fetch common secrets
      infisical.vault.read_secrets:
        login_data: "{{ infisical_login.login_data }}"
        project_id: b9c770a9-e3d7-4926-a2e0-2a1f43414f96
        env_slug: prod
        path: /ansible/common
        as_dict: true
      register: common_secrets
    - name: Fetch S3 ingest secrets
      infisical.vault.read_secrets:
        login_data: "{{ infisical_login.login_data }}"
        project_id: b9c770a9-e3d7-4926-a2e0-2a1f43414f96
        env_slug: prod
        path: /ansible/s3/ingest
        as_dict: true
      register: s3_ingest_secrets
    - name: Set secrets as variables
      set_fact: "{{ common_secrets.secrets | combine(s3_ingest_secrets.secrets) }}"
  tasks:
    - name: Get the latest commit hash
      shell: git rev-parse HEAD | head -c 8
      register: git_hash_result
      delegate_to: localhost
      changed_when: false
      when: lc_hash is not defined
    - name: Set lc_hash variable
      set_fact:
        lc_hash: "{{ lc_hash | default(git_hash_result.stdout) }}"
    - name: Debug the final values
      debug:
        msg:
          image: "registry.gitlab.com/letschurch/lets.church/probe-worker:{{lc_hash}}"
          identity: "{{ inventory_hostname }}"
    - name: Start lc-probe-worker container
      community.docker.docker_container:
        name: lc-probe-worker
        hostname: "{{inventory_hostname}}"
        image: registry.gitlab.com/letschurch/lets.church/probe-worker:{{lc_hash}}
        state: started
        recreate: true
        restart_policy: unless-stopped
        env:
          IDENTITY: "{{inventory_hostname}}"
          SERVICE_NAME: "probe-worker"
          AXIOM_DATASET: "{{AXIOM_DATASET}}"
          AXIOM_TOKEN: "{{AXIOM_TOKEN}}"
          TEMPORAL_ADDRESS: "{{TEMPORAL_ADDRESS}}"
          TEMPORAL_SHUTDOWN_GRACE_TIME: "{{TEMPORAL_SHUTDOWN_GRACE_TIME}}"
          MAX_CONCURRENT_ACTIVITY_TASK_EXECUTIONS: "{{MAX_CONCURRENT_ACTIVITY_TASK_EXECUTIONS}}"
          MAX_CONCURRENT_WORKFLOW_TASK_EXECUTIONS: "{{MAX_CONCURRENT_WORKFLOW_TASK_EXECUTIONS}}"
          S3_INGEST_REGION: "{{S3_INGEST_REGION}}"
          S3_INGEST_ENDPOINT: "{{S3_INGEST_ENDPOINT}}"
          S3_INGEST_BUCKET: "{{S3_INGEST_BUCKET}}"
          S3_INGEST_ACCESS_KEY_ID: "{{S3_INGEST_ACCESS_KEY_ID}}"
          S3_INGEST_SECRET_ACCESS_KEY: "{{S3_INGEST_SECRET_ACCESS_KEY}}"
          SENTRY_DSN: "{{SENTRY_DSN}}"
