name: Check

on: ["push", "pull_request"]

jobs:
  gateway:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "23.6.0"
          cache: "npm"
          cache-dependency-path: ./services/gateway/package-lock.json
      - name: Check gateway
        working-directory: ./services/gateway
        run: |
          npm install
          npm run check
  web:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "23.6.0"
          cache: "npm"
          cache-dependency-path: ./services/gateway/package-lock.json
      - name: Check web
        working-directory: ./apps/web
        run: |
          npm ci
          npm run check
  web-next:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.34"
      - name: Check web-next
        working-directory: ./apps/web-next
        run: |
          bun install
          bun run check
  scripts:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.34"
      - name: Check web-next
        working-directory: ./apps/web-next
        run: |
          bun install
          bun run check
  gateway-test:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "23.6.0"
          cache: "npm"
          cache-dependency-path: ./services/gateway/package-lock.json
      - name: Test gateway
        working-directory: ./services/gateway
        run: |
          npm ci
          npm test
